### ISSUE TITLE
Error when attempting to visit  https://localhost:8080 in Safari

### ISSUE THREAD

**Issue by Bhargavaa1** [mikeizbicki/cmc-csci143#101]
Hi Mike,
I am receiving an error that Safari can't establish a secure connection to the server localhost when I visit https://localhost:8080. I ran the given command and I am wondering if there is something wrong with my configuration.

Thanks,
Adi

**Comment by mikeizbicki** [comment]
The correct url is <http://localhost:8080> without the `s` in the scheme.

**Comment by iamasteriix** [comment]
@Bhargavaa1 did the solution work?

**Comment by Bhargavaa1** [comment]
Yes it did! Thanks Mike.
