### ISSUE TITLE
Problem connecting to localhost after running flask

### ISSUE THREAD

**Issue by jzlilili** [mikeizbicki/cmc-csci143#103]
Hello,
I'm working on lab 1, and running into problems with the last step. After I run the 
```
docker run -d -p 5000:5000 flask-tutorial
```
command with an altered port address, I'm logging out and then back in using the 
```
ssh username@134.173.191.241 -p 5055 -L 8080:localhost:PORT
```
command, and restarting Docker.  However, when trying to connect to http://localhost:8080 it seems like the site can't be reached, and I get the error
```
channel 3: open failed: connect failed: Connection refused
```
in the shell. I'm wondering if there was anything wrong with the order of the commands or the configuration?

**Comment by iamasteriix** [comment]
I believe mine constitutes of the same problem. Somehow, the server is refusing to accept any browser or `curl` requests.

 I ssh'd with port forwarding as both `ssh username@server.com -p 1234 -L 8080:localhost:DOCKER_PORT` and `ssh username@server.com -p 1234 -L 8080:127.0.0.1:DOCKER_PORT` and I have `ExecStart=/home/username/.local/bin/dockerd-rootless.sh`.

Right now, my server is logging the same message as @jzlilili 's every time I run `curl` or the browser tries to make a connection.

**Comment by Tonnpo** [comment]
I have the same issue when running the command `docker run -d -p ${UID}:5000 flask-tutorial`. Then, I took off the `-d` flag to not use **detach mode**.  I found out that there was an error in my `app.py` as below:
```
**Traceback (most recent call last):
  File "app.py", line 1, in <module>
    from flask import Flask
  File "/usr/local/lib/python3.5/dist-packages/flask/__init__.py", line 1, in <module>
    from markupsafe import escape
ImportError: cannot import name 'escape'**
```
So, as the error suggested (yours might be different), I believe I might not have **markupsafe** installed. Therefore, I inspected the output of the command 
```
docker built -t flask-tutorial .
```
I saw something like
```
Successfully installed Flask-2.0.2 Jinja2-3.0.3 MarkupSafe-0.0.0 Werkzeug-2.0.2 click-8.0.3 dataclasses-0.8 importlib-metadata-4.10.1 itsdangerous-2.0.1 typing-extensions-4.0.1 zipp-3.7.0
```
It seems to me that the version of **MarkupSafe** is messed up. I tried changing different version of **Flask** and **MarkupSafe** to see if there is any compatibility. No luck, I did not get it working.  Finally, I decided to change the version of **ubuntu** to be `18.04` and `python` to be `python3` in `Dockerfile` and got it working

**Comment by iamasteriix** [comment]
@Tonnpo
> So, as the error suggested (yours might be different), I believe I might not have **markupsafe** installed. Therefore, I inspected the output of the command

I didn't have a problem with that, but your comments suggested that I configure my files to use similar settings as the server. Thanks!

If anyone needs this:
- `lsb_release -d` shows Ubuntu version `Ubuntu:18.04`
- you want to have `python3-pip` and `python3-dev`, and the entrypoint is `"python3"`
- you also want to run `pip3` to install the modules in `requirements.txt`. For example, I had `RUN pip3 --no-cache-dir install -r requirements.txt`
- run `which flask` to find where it is and remove it, just to make sure you install `pip3`'s Flask, as below
- `pip3 install Flask`
- `docker build -t <whatever_name_you_want> .` should work now
- you can confirm this by running `docker images`

**Comment by axelahdritz** [comment]
My flask app worked the first time I ran it, but after attempting to rerun it, I am getting the same error message as you all, printed a dozen time or so, even after adjusting my settings to correspond with the server's and following all of the helpful advice above. To be clear, I am receiving the error message below:
```
channel 3: open failed: connect failed: Connection refused
```
and the error in my firefox browser reads:
```
The connection to the server was reset while the page was loading.
```
