### ISSUE TITLE
problem doing ssh port forwarding on putty

### ISSUE THREAD

**Issue by dustin-lind** [mikeizbicki/cmc-csci143#104]
Hi Mike, 

I'm trying to configure putty to enable port forwarding, but I'm running into trouble even after following the directions provided in the link you posted in the `week_01/README.md`. Attached below are screenshots of my configurations in the putty window. After entering in the information, I click open and login into the lambda server using my credentials.

![Screenshot 2022-01-29 123747](https://user-images.githubusercontent.com/78048849/151676947-213f58b0-2c7c-4147-a976-c10b57231ecf.png)
![Screenshot 2022-01-29 123729](https://user-images.githubusercontent.com/78048849/151676948-a21fda9c-0623-43ab-9bce-282e6f773b45.png)

When I enter in `localhost:8080` to the URL line in the web browser, I get the following error
![Screenshot 2022-01-29 124643](https://user-images.githubusercontent.com/78048849/151677040-2b919be8-70d0-47c1-9300-0665524f1b2a.png)

I'm curious if you can tell me what I am doing wrong.

Best,

Dustin

**Comment by Tonnpo** [comment]
I am not exactly sure what causes an issue but in my case, I used `localhost:5000` in the destination field.

**Comment by leafsphere** [comment]
@Tonnpo's solution worked for me! Thank you so much!

**Comment by dustin-lind** [comment]
Worked for me too. Thanks @Tonnpo!
