### ISSUE TITLE
channel 3: open failed: connect failed: Connection refused

### ISSUE THREAD

**Issue by afroCoderHanane** [mikeizbicki/cmc-csci143#109]
Hey Mike,
after connecting to the lambda server and also successfully running a 

```
docker run -p 8728:5000 -d flask-tutorial 

```
for the last part of the lab,
I get that message above that I think might be related to the permission issue I had.
I did the rerouting of the localhost and when I try it out on the browser it doesn't display. 
I also notice that:

```
docker ps

```
do not display the listing of the container when I run 

```
docker build -t flask-tutorial:latest .

```
Only for this problem. When I tried going back to the video, I  was able to see the list of the containers.

I am using Ubuntu Linux!!!

**Comment by iamasteriix** [comment]
@afroCoderHanane 

This error isn't necessarily related to docker; it has more to do with port forwarding and whatever services are running in those ports.

That said, what error or message do you get after running your `docker build -t flask-tutorial:latest .` command?

**Comment by afroCoderHanane** [comment]
```The docker build -t flask-tutorial``` render successfully after I have done some modification notably the **MAINTAIN** change Ubuntu version from v16 to just  **ubuntu**  and even the ```docker run``` do not display any notable error!

**Comment by mikeizbicki** [comment]
I believe this is not a networking issue, but rather something related to the docker/python code.  I think the error is probably pretty subtly and will be easiest to resolve in person.  Let's meet up either after class/in office hours.

**Comment by iamasteriix** [comment]
@mikeizbicki did we find out about whatever caused this error?

**Comment by mikeizbicki** [comment]
This error was resolved in office hours (@afroCoderHanane correct me if I'm wrong).  I'm closing since there's not enough info here to detail the error/solution for other students.
