### ISSUE TITLE
Error Building From docker-compose.prod.yml

### ISSUE THREAD

**Issue by DestrosCMC** [mikeizbicki/cmc-csci143#113]
When I ran:
```
docker-compose -f docker-compose.prod.yml up -d --build
```
I encountered this error:
```
The command '/bin/sh -c flake8 --ignore=E501,F401 .' returned a non-zero code: 1
ERROR: Service 'web' failed to build: Build failed
```
It seems like flake8 doesn't like `./env/lib/python3.6/site-packages/setuptools/command/`. 

Is there a way to fix this?

**Comment by mikeizbicki** [comment]
It doesn't look like you're including the full error message here, so it's a bit hard to tell what's going on.  (As a general rule, you should always copy and paste the ENTIRE output of a command into a github issue, even (or especially!) if it's multiple pages long.)

My guess: `flake` is a code linter that ensures python is properly formatted.  Most likely what's going on is that `flake` has been updated to include new code formatting rules, and so the python files need to be updated to follow those new rules.  But without the full output, I can't say for sure.

**Comment by mikeizbicki** [comment]
Closing since we resolved this in office hours.
