### ISSUE TITLE
Having Trouble Updating python3.6 to python3.9

### ISSUE THREAD

**Issue by Bhargavaa1** [mikeizbicki/cmc-csci143#120]
Hi Mike and the class,
Has anyone been able to update python3.6 to python3.9 on the lambda server? I have been trying homebrew and pip but I have been unsuccessful so far.

Thanks,
Adi

**Comment by mikeizbicki** [comment]
There is no need to upgrade python.  Just change `python3.9` to `python3` in the instructions.

**Comment by Bhargavaa1** [comment]
Sounds good. I was able to make it work with python3.
