### ISSUE TITLE
Error: cannot import name 'app' after running manage.py

### ISSUE THREAD

**Issue by yilinli22** [mikeizbicki/cmc-csci143#122]
I followed the tutorial and when I went to the step:
```
(env)$ export FLASK_APP=project/__init__.py
(env)$ python manage.py run
```
I got the error message:
```
Traceback (most recent call last):
  File "manage.py", line 3, in <module>
    from project import app
ImportError: cannot import name 'app'
```
From the "web" directory, I tried to run 
```
pip3 install app
```
But I still got the same error message.
I also went through the [issue#116](https://github.com/mikeizbicki/cmc-csci143/issues/116) but still getting the same error message.
Can anyone help me? Thanks a lot!

**Comment by iamasteriix** [comment]
@yilinli22 
Is your `__init__.py` file in the `project` folder?

**Comment by yilinli22** [comment]
> @yilinli22 Is your `__init__.py` file in the `project` folder?

Yes it is.

**Comment by iamasteriix** [comment]
Did you necessarily call that file `__init__.py`, with double underscores before and after `init`?

**Comment by yilinli22** [comment]
> Did you necessarily call that file `__init__.py`, with double underscores before and after `init`?

Oh I changed the name into one underscore before and after `init` everywhere. Should I change it back?

**Comment by yilinli22** [comment]
> > Did you necessarily call that file `__init__.py`, with double underscores before and after `init`?
> 
> Oh I changed the name into one underscore before and after `init` everywhere. Should I change it back?

I collaborate with the other student and he used double underscore but he still got the same error message.

**Comment by iamasteriix** [comment]
The `__init__.py` file marks a folder as a package (in python), so I would recommend trying that first, see what it does.

**Comment by yilinli22** [comment]
> The `__init__.py` file marks a folder as a package (in python), so I would recommend trying that first, see what it does.

Now I got the error message in [issue#116](https://github.com/mikeizbicki/cmc-csci143/issues/116), and I followed the steps there and ran:
```
python manage.py -p ${UID}
```
Got the error message:
```
Usage: manage.py [OPTIONS] COMMAND [ARGS]...
Try 'manage.py --help' for help.

Error: No such option: -p
```
Should I install any packages?

**Comment by iamasteriix** [comment]
Did you install `flask` with `pip` or `pip3`? I think you're going to run into problems with `pip3`.

But first, try running
```
python3 manage.py -p ${UID}
```

If the error persists, `deactivate` the environment, activate a new one with python2, then run the command again, see what that does. So basically,
```
deactivate
python -m venv env
source env/bin/activate
pip install flask==1.1.2
```

**Comment by yilinli22** [comment]
> python -m venv env

Thank you! I tried running:
```
deactivate
python2 -m venv env
```
There is an error message:
```
/usr/bin/python2: No module named venv
```

**Comment by iamasteriix** [comment]
Did you try with just `python`, as opposed to `python2`?

**Comment by yilinli22** [comment]
> Did you try with just `python`, as opposed to `python2`?

Yes, and the error message is the same.

**Comment by iamasteriix** [comment]
I see. Try `python3`.

**Comment by yilinli22** [comment]
And it turns back to the previous error after  I ran 
```
python manage.py -p ${UID}
```
or after I ran:
```
python3 manage.py -p ${UID}
```
The error message is
```
Usage: manage.py [OPTIONS] COMMAND [ARGS]...
Try 'manage.py --help' for help.

Error: No such option: -p
```
If I ran 
```
python2 manage.py -p ${UID}
```
the error message is
```
Traceback (most recent call last):
  File "manage.py", line 1, in <module>
    from flask.cli import FlaskGroup
ImportError: No module named flask.cli
```

**Comment by iamasteriix** [comment]
@yilinli22 
I'll try to document a comprehensive workflow for the commands and see if that helps.

If your `env` is still active, `deactivate` it. Then
```
python3 -m venv env
source env/bin/activate
# you can skip the pip install flask step if you did it before
export FLASK_APP=project/__init__.py
export FLASK_ENV=development # this is an optional step
flask run -p ${UID}
```

You should get something that looks like this
```
 * Serving Flask app "project/__init__.py" (lazy loading)
 * Environment: development
 * Debug mode: on
 * Running on http://127.0.0.1:<your_port_id>/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 123-456-789
```

I realize that the `flask run -p <your_port_id>` doesn't necessarily say anything about your `manage.py`. But if it ran successfully, you could go ahead and run
```
python3 manage.py run -p ${UID}
```

You should get the same results.

**Comment by yilinli22** [comment]
> 

This works. Thank you!
