### ISSUE TITLE
What port should I use for prod?

### ISSUE THREAD

**Issue by erdsal4** [mikeizbicki/cmc-csci143#123]
I have been using port ($UID) for the web service, but then the guide introduced the nginx service running at 1337. Should I randomly select a port for nginx?

**Comment by mikeizbicki** [comment]
In all of these instructions that use docker/docker-compose, you'll only ever want to change 1 port: the port that gets exposed to the lambda server.  All the ports that are internal to the various containers should not get changed.  In these instructions, nginx is the only service being exposed, and the `docker-compose.prod.yml` file is routing port 1337 on the lambda server to port 80 on the container.  You'll want to change the 1337 to something else so as not to conflict with other students.  It doesn't matter what you change it to.
