### ISSUE TITLE
docker compose permission denied

### ISSUE THREAD

**Issue by ohorban** [mikeizbicki/cmc-csci143#124]
Hi Mike and everyone else. I am getting an error 
```
-bash: /usr/bin/docker-compose: Permission denied
```
after running `docker-compose build` in my web folder.
I have a `docker-compose.yml` file in my web directory but for some reason, docker is trying to run a wrong docker-compose file (i think)
I tried specifying the path to the correct docker-compose file by running
```
docker-compose -f /home/Oleksandr.Horban.24/flask-on-docker/services/web/docker-compose.yml build
```
but i get the same error.

Did anyone else run into the same error or knows how to fix this?

**Comment by Tonnpo** [comment]
I ran into the same issue. I think it might have to do with the command `docker-compose` which reference to a file we do not have permission to execute. My way around this is to create another virtual environment at the root of the project, enter the environment and then install **docker-compose** through
```
pip install docker-compose
```
Then, make sure that we are in this environment and then try run `docker-compose` again. Hope this helps!

**Comment by mikeizbicki** [comment]
@Tonnpo's answer is mostly correct.  But I'll add that there's no need to create a virtual environment to install docker-compose.  You can just run the command 
```
$ pip3 install docker-compose
```
and then you'll have access to the command (assuming your `PATH` is set correctly).

**Comment by dabalus** [comment]
> @Tonnpo's answer is mostly correct. But I'll add that there's no need to create a virtual environment to install docker-compose. You can just run the command
> 
> ```
> $ pip3 install docker-compose
> ```
> 
> and then you'll have access to the command (assuming your `PATH` is set correctly).

After running this, I am still getting Permission denied, and then I run 
```
echo $PATH
```
 and this is the output
```
/home/dabalus/bin:/home/dabalus/.local/bin:/home/dabalus/.cabal/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

```
Is there something wrong with my path?

**Comment by afroCoderHanane** [comment]
System: UBUNTU Linux
I was getting the Permission denied also at first until I actually tried running 
```pip3 install docker-compose```
End up running into a snag again but it was due to the dependency ```cryptography``` not installing  and ```wasn't``` updating too to easily fix it. I went to the root folder. tried to upgrade pip3. end up working and reinstalling all the python dependencies. navigated back to the flask-on-docker folder and I was able to run the code locally without the ```venv```. I will highly suggest not using the venv at all because I later had to debug my code due to flake8 issue. and Thanks to @joeybodoia I saved 12-24 hours of research lol.

**Comment by mikeizbicki** [comment]
@dabalus If you're still having issues, it would help if you paste ALL the commands that you ran and their output (even/especially if it's multiple pages).  I'm not sure what's going on based on what you have.

@afroCoderHanane Thanks for the tips!  But FYI, you have lots of minor formatting issues with your post and how you're using code blocks that you should try to fix in the future.
