### ISSUE TITLE
Error building the production Dockerfile

### ISSUE THREAD

**Issue by afroCoderHanane** [mikeizbicki/cmc-csci143#125]
Hey @mikeizbicki 
![Screenshot from 2022-02-07 23-26-57](https://user-images.githubusercontent.com/49354774/152918555-1f4e9854-dd29-4a13-88ac-3f98c7e0cb1d.png)
I am having this issue related to flake-8 which is prohibiting me from building I believe. I followed the convention when writing my .py files but I still run into a snag. Can you please take a look at  the pictures I attached and see what my cause the prooblem?
Thanks.

**Comment by afroCoderHanane** [comment]
Issues solved : I had two env folder in my repository. moved them out of the flask-on-docker repo and it runs.
It was a flake8 issue

**Comment by mikeizbicki** [comment]
I'm glad you got it resolved :)

In the future, don't post screnshots, though.  They have a number of limitations:
1. more work than just copy/pasting
2. prevent other people from copy/pasting
2. are not indexable by google
3. the size is limited by your screen size

When posting issues to other repos outside of class, people will be much less likely to help if you use screenshots than if you copy/paste into a code block.
