### ISSUE TITLE
Questions about Production Credentials & Media folder

### ISSUE THREAD

**Issue by katiewu71** [mikeizbicki/cmc-csci143#126]
Hi Prof. Mike,

I was wondering if it was fine to upload docker-compose.yml since it does have environment variable values stored. Do those count as production credentials? Also, my flask-on-docker github repo doesn't include a media directory, since it was empty (wasn't automatically added through the "git add ." command). Is that fine?

Thanks!
Katie

**Comment by mikeizbicki** [comment]
> I was wondering if it was fine to upload docker-compose.yml since it does have environment variable values stored. Do those count as production credentials?

The only file for this hw that contains production credentials is `.env.prod.db`.  Environment variables in general are not always credentials, and the credentials that happen to be stored in `docker-compose.yml` are for the development environment and not the production environment.

> Also, my flask-on-docker github repo doesn't include a media directory, since it was empty (wasn't automatically added through the "git add ." command). Is that fine?

A limitation of git is that there is no way to add empty folders to a git repo.  So if your `media` folder is empty (which is fine), then it cannot be added.

----

PS. In the future, distinct questions should be on distinct lines to make it easier to quote them in a reply.  And filenames should be in backticks.
