### ISSUE TITLE
Problem 06 and 06b in pagila-hw2

### ISSUE THREAD

**Issue by Tonnpo** [mikeizbicki/cmc-csci143#129]
Hi Mike,

I have a question regarding **pagila-hw2**. If I already use `LEFT JOIN` in problem 6, should I

1. Use `NOT IN` and a subquery in problem 6 and copy my `LEFT JOIN` solution to 6b. Or
2. Copy `LEFT JOIN` solution to 6b is fine

Thanks very much for your time and help!

**Comment by mikeizbicki** [comment]
My intention was that 6 would use the `NOT IN` operator + subquery, and 6b would use the `LEFT JOIN`.  They shouldn't both be the same solution.

**Comment by Tonnpo** [comment]
Thanks very much for clarifying!
