### ISSUE TITLE
Cannot connect to Docker daemon?

### ISSUE THREAD

**Issue by amytam01** [mikeizbicki/cmc-csci143#14]
Note: Moved my issue here (copy pasted)

So I've ironed out some of the initial problems as mentioned by @mikeizbicki and ended up redoing the entire process and now have the correct `export` command in my `.bashrc` file. I've also made sure (again and again) that my docker files are not in `bin` but `.local/bin`.  I've also followed Sam's suggestions and made sure my unit file was correct in `~/.config/systemd/user/docker.service`

Now when I run `systemctl --user start docker`
I have no problems, but when I try to run `docker run ubuntu`
I get the following error: 
`Cannot connect to the Docker daemon at unix:///run/user/1137/docker.sock. Is the docker daemon running?`
so usually I attempt `systemctl --user daemon-reload`
I think I got this error after moving my files from `bin` to `.local/bin` and I've reinstalled Docker at least 5 times (so maybe that's the problem?) I always assumed that my files were being rewritten each time they were moved. Thanks!

Edit: I've learned so much about docker commands and process after all of these issues, but I still can't get it to work xD

**Comment by mikeizbicki** [comment]
You have different error messages in this issue and in #7, so I'm not sure which one is the actual problem.  Let me know if the fix I mentioned there doesn't work.

I'm going to close this issue and keep the rest of the discussion in #7 since we've already started there.
