### ISSUE TITLE
Baby came today... no class rest of the week

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/cmc-csci143#140]
My wife gave birth to our new baby (Aaron Izbicki) today.

For how this affects class:

1. Class+office hours are cancelled for the remainder of this week.

1. There is no need to turn in the "Row Overhead Take Home Exercise".  Everyone gets full credit :)

1. Pagila homeworks all have the same due dates.

1. Sometime before next week I'll post another update to include details about when we'll resume class, when the midterm will be, and any further adjustment to hw.

I realize Aaron has brought a lot of uncertainty into your all's semester in terms of scheduling for this class, and I appreciate your willingness to be flexible.

Finally, here's some pictures:

![aaron2](https://user-images.githubusercontent.com/1052630/155242518-103775f5-209a-494d-a927-c11f9aaed47f.jpg)

![aaron](https://user-images.githubusercontent.com/1052630/155241663-0d857db9-7049-495d-912a-fd6092883e91.jpg)

**Comment by DestrosCMC** [comment]
Congratulations Mike!

**Comment by afroCoderHanane** [comment]
Congrats Mike ❤️. The baby is so cute. Sending you and your wife plenty of love 🎉🎉🎉🎉🎉.

**Comment by dabalus** [comment]
Congrats Mike

**Comment by katiewu71** [comment]
Congratulations Prof. Mike!!

**Comment by axelahdritz** [comment]
Congratulations Mike!

**Comment by vbopardi** [comment]
Congrats! Was he born at 2:22? (we NEED to know)

**Comment by samcbogen** [comment]
Congratulations Mike and Mrs. Izbicki! Aaron is adorable!

**Comment by Bhargavaa1** [comment]
Congrats Mike!

**Comment by alex-muehleisen** [comment]
Congrats Mike!!

**Comment by leafsphere** [comment]
He's so cute! Congrats Mike!!

**Comment by dustin-lind** [comment]
Congratulations Mike! Very exciting news!

**Comment by Tonnpo** [comment]
Congrats Mike!

**Comment by joeybodoia** [comment]
Congrats Mike! Very excited for you!
