### ISSUE TITLE
Homework : Twitter Map Reduce

### ISSUE THREAD

**Issue by afroCoderHanane** [mikeizbicki/cmc-csci143#141]
Hey everyone,
I don't know if someone attempted the Twitter Map reduce and can provide more clarification on the last part where we are using the
```
$ ./src/visualize.py --input_path=PATH --key=HASHTAG | head > viz/HASHTAG

```
So I changed the `PATH` with `reduced.lang`  the  `HASHTAG` with  `#coronavirus` and use output redirection to `viz/HASHTAG` but it is only creating a `#coronavirus` file in the viz directory but I am uncertain if that should be what we expect so if that is what is the expected result please  let me know or any clarifying tip will be greatly appreciated.

**Comment by mikeizbicki** [comment]
>it is only creating a `#coronavirus` file in the viz directory but I am uncertain if that should be what we expect so if that is what is the expected result please let me know or any clarifying tip will be greatly appreciated.

This is the expect result for the command you ran, but it is not what the final result should be.  You should create a different file for each of the hashtags by running the `visualize.py` script multiple times.  The easiest way to accomplish this is via a for loop that looks something like
```
for hashtag in '#coronavirus' '#corona'; do
    ./src/visualize.py --key=$hashtag <more stuff here>
done
```
