### ISSUE TITLE
"withheld_in_countries" and other tweet keys

### ISSUE THREAD

**Issue by axelahdritz** [mikeizbicki/cmc-csci143#146]
Hey!

I was wondering whether anyone knew how to incorporate certain columns in the `pg_normalized` tables. For instance, I get this error when trying to insert the `withheld_in_countries` value into the users table:
```
load normalized
2022-03-18 11:13:14.312903 test-data.zip
Traceback (most recent call last):
  File "load_tweets.py", line 431, in <module>
    insert_tweet(connection,tweet)
  File "load_tweets.py", line 174, in insert_tweet
    'withheld_in_countries': tweet['user']['withheld_in_countries']
KeyError: 'withheld_in_countries'
Command exited with non-zero status 1
0.33user 0.06system 0:00.40elapsed 95%CPU (0avgtext+0avgdata 43388maxresident)k
0inputs+0outputs (0major+13687minor)pagefaults 0swaps
load denormalized
0.27user 0.01system 0:00.92elapsed 31%CPU (0avgtext+0avgdata 3216maxresident)k
0inputs+0outputs (0major+332minor)pagefaults 0swaps
COPY 9998
```
This seems to be due to the tweet lacking that JSON key. Everything seems to work alright when I exclude it from my SQL code. How can I incorporate this info into the table?

I would be grateful for any help in this matter!

**Comment by mikeizbicki** [comment]
Good question!

One of the difficulties with working with json data (and denormalized data more generally) is that the schema is not fixed, and so attributes may or may not be present.  The way to convert into a normalized form is to use a `NULL` sql value (`None` python value) in the corresponding normalized column.

In python, the easiest way to do this is with the `.get` dictionary method, which lets you specify a default value for when the key entry doesn't exist.  For example, my solution extracts the `withheld_in_countries` column using code that looks like:
```
tweet['user'].get('withheld_in_countries',None)
```
