### ISSUE TITLE
How can we pretty print example.json1 to easily see the structure of the file?

### ISSUE THREAD

**Issue by dustin-lind** [mikeizbicki/cmc-csci143#147]
Hi Mike and the rest of the class!

I was wondering if there was a way to pretty print `example.json1` in the `text-data.zip` to see the structure of the JSONB file? I think this would be helpful to determine what layers we need to index into to extract a certain field when inserting data into our db.

For example, it's hard to see from the raw JSONB file that to access the `users_mentions` field you sometimes need to index like:
```
tweet['extended_tweet']['entities']['user_mentions']
```
and not simply
```
tweet['user_mentions']
```

If you didn't pretty print, how did you go about seeing the `example.json1` file structure?

Best,

Dustin

**Comment by mikeizbicki** [comment]
Pretty printing is a great idea.  There's lot of ways to achieve this, but something like the following will work straight from the command line:
```
$ unzip -cq test-data.zip | head -n1 | python3 -m json.tool
```

**Comment by dustin-lind** [comment]
Awesome, thank you!
