### ISSUE TITLE
SQL Alchemy error

### ISSUE THREAD

**Issue by afroCoderHanane** [mikeizbicki/cmc-csci143#151]
Hey mike or class, 
Do anyone knows what this error message is referring to:
```
load normalized
Traceback (most recent call last):
  File "load_tweets.py", line 4, in <module>
    import sqlalchemy
ModuleNotFoundError: No module named 'sqlalchemy'
Command exited with non-zero status 1
0.12user 0.02system 0:00.14elapsed 99%CPU (0avgtext+0avgdata 24228maxresident)k
0inputs+0outputs (0major+3431minor)pagefaults 0swaps

```

Thanks for the help!

**Comment by joeybodoia** [comment]
I'm pretty sure this is because you do not have SQLAlchemy installed on the lambda server. 

You can run `pip3 list | grep -iF sqlalchemy` to see if SQLAlchemy is installed. 

If not, running `pip3 install SQLAlchemy` should resolve this issue.

**Comment by afroCoderHanane** [comment]
Thanks joey, it worked
