### ISSUE TITLE
Transactions and Locks Notes Problem 24

### ISSUE THREAD

**Issue by DestrosCMC** [mikeizbicki/cmc-csci143#152]
For problem 24, session 1 Creates table t, begins a transaction, and locks table t in row exclusive mode. Session 2 creates an index concurrently on t (a), which gives it a share update exclusive lock. 

I looked in table 13.2 and there should be no conflict between an existing row exclusive lock and a share update exclusive lock, so why does the line in session 2 block?

**Comment by mikeizbicki** [comment]
Fantastic question.  We'll go over this in class today.
