### ISSUE TITLE
Trouble connecting to lambda server

### ISSUE THREAD

**Issue by joeybodoia** [mikeizbicki/cmc-csci143#154]
Hey Mike, 

I'm unable to connect to the lambda server for some reason. When I try to connect, I'm not prompted for my password, rather, I see the following:

![Screen Shot 2022-03-30 at 11 19 58 PM](https://user-images.githubusercontent.com/53023300/160989265-0541ee26-d027-4d39-8b55-8c468f4c4415.png)
 
And it stays in this weird buffer stage until I hit `ctrl c`

![Screen Shot 2022-03-30 at 11 21 56 PM](https://user-images.githubusercontent.com/53023300/160989544-61274ff9-d8ba-4345-9308-05f9255dd9e4.png)

Dustin said that he was running into the same issue.

**Comment by dustin-lind** [comment]
Mine was not working last night, but it appears to be working fine this morning

**Comment by mikeizbicki** [comment]
Not sure what the problem was exactly, but it the lambda server itself wasn't down.  Running 
```
$ uptime
12:39:02 up 148 days, 21:47,  8 users,  load average: 0.04, 0.04, 0.05
```
you can check how long a computer has been on for, and we see that the lambda server was definitely on.
