### ISSUE TITLE
Question 62 locks and transactions

### ISSUE THREAD

**Issue by joeybodoia** [mikeizbicki/cmc-csci143#157]
Hey Mike,

I'm confused on why `line 10` on `question 62` results in a block instead of an error. 

From my understanding, 
```
insert into u values (8);
``` 
on `line 8 `would defer (because of deferrable initially deferred) a 
```
select * from t where a=8 for key share
``` 
to check if the value 8 is present in table `t`. This leads me to expect that `line 10` would error because the aforementioned 
```
select * from t where a=8 for key share
``` 
would execute upon the `commit` on `line 10`, resulting in an error because the value 8 is not in table `t` at that point in time. However, given that `line 10` results in a block, I'm curious if `line 8` is instead deferring a 
```
select * from t where a=8 for update
```
 or
 ```
select * from t where a=8 for share
```
 because this would create a `ROW SHARE` lock on table `t`, which would conflict with the `EXCLUSIVE` lock that was created on `t` on `line 9`, thus, explaining the block on `line 10`.

Any advice on this question would greatly appreciated.

**Comment by joeybodoia** [comment]
To follow up this issue, running 
```
select relation::regclass, mode, pid, granted from pg_locks where locktype='relation';
```  
after executing `line 10` shows that `line 10` creates a `ROW SHARE` lock on table `t`, which fails, and thus causes the block. However, I don't quite understand why the deferred `select` check from `insert into u values (8)` creates that `ROW SHARE` lock upon commit.

**Comment by mikeizbicki** [comment]
I'd be happy to go over this with you in person before class/you take the quiz today.
