### ISSUE TITLE
SQLAlchemy could not connect to server

### ISSUE THREAD

**Issue by jzlilili** [mikeizbicki/cmc-csci143#158]
Hi Prof Mike,
I'm running to the following error when running both my `load_tweets_sequential.sh` and `load_tweets_parallel.sh` files:

```
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 31013?
```
I've changed my port numbers multiple times, checked to make sure the port numbers matched the ones in `docker-compose.yml`, and pruned my docker volumes, but still can't figure out why the error is occurring. I was able to run `load_tweets_sequential.sh` an hour ago with no problems, and haven't made any changes to the file since. I also ran into this issue on and off when working on the twitter-postgres homework. Do you know what could be causing my connection problems?

**Comment by afroCoderHanane** [comment]
I did run into this error, but I will just advise you to 
`docker-compose down` , `docker volume prune` and run `docker-compose up -d —build` and make sure you change your port number are matching in the dockerfile and the load_tweets sh files.

**Comment by dustin-lind** [comment]
I also ran into this same error. If you rebuild your docker container with the correct port numbers and you still find yourself running into the same error, check your schema file to make sure you don't have an extra comma somewhere or you are missing a comma. I accidentally left an extra comma in my schema fill after removing the primary key and foreign key constraints and it was not allowing me to build my container with the `pg_normalized_batch` schema.

**Comment by Tcintra** [comment]
Alternatively, if you are convinced you have the port numbers correctly then I found that sometimes the ```docker-compose up -d --build``` doesn't actually start some of the containers. Particularly, if you check ```docker ps``` and you don't have all three containers running, then you will get the SQLAlchemy OperationalError. If the container is not running then sqlAlchemy can't connect to the server. This happened to me with the normalized batch container because I had a typo in my schema for pg_normalized_batch, so you might want to check that file.

**Comment by jzlilili** [comment]
Thanks for the help! It seems like the normalized batch container also wasn't running for me. I didn't find a typo in my schema file, but rerunning the `docker-compose up -d --build` command fixed my issue.
