### ISSUE TITLE
Quota for Account

### ISSUE THREAD

**Issue by choughton21** [mikeizbicki/cmc-csci143#16]
Hi professor,

I am trying again to download the file. I tried to do manual installation and I am not even able to extract the file. 

Here is my disk usage in home, it is tiny, but I am still not able to extract the file. 

///`
lambda-server:~/.cache $ du -h
124M    ./docker
190M    .
`

Here is the error 
`
tar: docker/docker-init: Cannot write: Disk quota exceeded
docker/docker-proxy
tar: docker/docker-proxy: Cannot write: Disk quota exceeded
`

**Comment by mikeizbicki** [comment]
Hmm... it looks like your account was accidentally created with the wrong set of permissions, so you didn't have enough disk space to get docker installed.  It should be fixed now.  Sorry about that.

----

PS.  For multiline code blocks, you need to do 3 backticks on a single line by themselves for the formatting to work correctly.  (You only have a single backtick.)
