### ISSUE TITLE
Error loading data (load_tweets_batch.py)

### ISSUE THREAD

**Issue by leafsphere** [mikeizbicki/cmc-csci143#161]
Hi, I was trying to load data into the `pg_denormalized` and `pg_normalized_batch` services, and I ran into the following error under `load pg_normalized_batch` in the output:

```
psycopg2.errors.UndefinedTable: relation "urls" does not exist
LINE 2:     insert into urls
                        ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "load_tweets_batch.py", line 458, in <module>
    insert_tweets(connection,tweets,args.batch_size)
  File "load_tweets_batch.py", line 175, in insert_tweets
    _insert_tweets(connection, tweet_batch)
  File "load_tweets_batch.py", line 212, in _insert_tweets
    user_id_urls = get_id_urls(tweet['user']['url'])
  File "load_tweets_batch.py", line 55, in get_id_urls
    res = connection.execute(sql,{'url':url}).first()
```

It seems like the `load_tweets_batch.py` file in this repo still has the function `get_id_urls`, which seems to be throwing errors when trying to load tweets into the normalized batch. Should we replace this file with [that of the solutions branch](https://github.com/mikeizbicki/twitter_postgres_parallel/blob/solution/load_tweets_batch.py) from the previous homework?

**Comment by mikeizbicki** [comment]
Eeek... it looks like a bad merge conflict caused the `master` branch to get the old version of the `load_tweets_batch.py` file instead of the solution.  I've just fixed this and reuploaded.  If you run a `git pull` command you should get the updated file and things should work.

Sorry about that.

**Comment by leafsphere** [comment]
Thanks Mike, the data loads correctly now!
