### ISSUE TITLE
Latex Question

### ISSUE THREAD

**Issue by DestrosCMC** [mikeizbicki/cmc-csci143#163]
Many of the practice questions say that uncommenting the ```\printanswers``` line will display the answers, but what is the process to view the answers? Is there a special program we have to download?

**Comment by mikeizbicki** [comment]
You will have to build the latex file into a pdf file.  There's many tools to do that.  On any linux/mac system (such as the lambda server), you can use the `pdflatex` command.  MikTek is a popular latex program for mac/windows.  And overleaf is a website that will work with any system.

Alternatively, you can just look at the source, which contains the answers embedded into the tex files next to each question.

**Comment by DestrosCMC** [comment]
Got it, thank you!
