### ISSUE TITLE
Confirming that we need to create `sql.denormalized` directory

### ISSUE THREAD

**Issue by dustin-lind** [mikeizbicki/cmc-csci143#166]
Hi Mike,

I just wanted to confirm that we need to create the `sql.denormalized` directory in our `twitter_postgres_index` repo, and it is not the case that you did not forget to push it to the repo. You mentioned in the README file:

> You will have to modify the files in `sql.denormalized` so that they produce the same output as the files in `sql.normalized_batch`.

However, `sql.denormalized` currently does not exist.

Just checking! Thanks.

Best,

Dustin

**Comment by mikeizbicki** [comment]
That's correct.  There is not supposed to be a `sql.denormalized` directory.  The instructions are a bit unclear here, and I would be open to a pr clarifying them.
