### ISSUE TITLE
Question on Integrated Questions packet

### ISSUE THREAD

**Issue by joeybodoia** [mikeizbicki/cmc-csci143#169]
Question #5 of the integrated questions section states 
```
Create index(es) so that the following query could use an index only scan. Do not create any unneeded indexes; if no new indexes are needed say so.
SELECT count(*)
FROM tweets
WHERE id_user=:id_user
     AND created_at < :hi
     AND created_at >= :lo;
```
In the lecture video, the answer you give for this question is 
```
CREATE INDEX on tweets(id_user, created_at)
```
However, the week 11 notes state that one of the requirements for index only scans is 
```
All of the columns returned by the SELECT query and all columns in the WHERE clause are present in the index
```

Wouldn't this mean that since the above query is selecting `count(*)` that we would need to include all columns of the `tweets` table in the index because the `select` query is returning all columns from `tweets`?

So, something like 
```
CREATE INDEX on tweets(id_user, created_at, id_tweets, in_reply_to_user_id, text)
```

Also, for the take-home quiz, are we assuming the indexes are cumulative in the sense that if we created an index on question 4 we then assume on question 5 that the index from question 4 is present? Or is each question isolated?

**Comment by mikeizbicki** [comment]
If the query were `SELECT *`, then you'd be right.  But the `*` in `count(*)` has a different meaning and doesn't actually refer to all of the rows.  There's a big rabbit hole to go down here, but https://stackoverflow.com/questions/2710621/count-vs-count1-vs-countpk-which-is-better would get you started.
