### ISSUE TITLE
Indexes not building for normalized queries 3-5?

### ISSUE THREAD

**Issue by DestrosCMC** [mikeizbicki/cmc-csci143#171]
Dustin and I have been running into a problem where queries 1,2 run in around a second, but then 3,4, and 5 take around 2 minutes to finish running. 

Our indexes look like this: 

```
  1 -- Q1, Q2
  2 CREATE INDEX tweettags_idx_tagtweets ON tweet_tags(tag, id_tweets);
  3 CREATE INDEX tweettags_idx_tweetstag ON tweet_tags(id_tweets, tag);
  4 -- Q3
  5 CREATE INDEX tweets_idx_lang on tweets(id_tweets, lang);
  6 CREATE INDEX tweets_idx_lang2 on tweets(lang);
  7 -- Q4,5
  8 CREATE INDEX tweets_idx_gin on tweets USING gin(to_tsvector('english', text));
```

Any help would be appreciated, thank you!

**Comment by mikeizbicki** [comment]
You should verify that the indexes actually exist by running `\d tweeets` in psql.  If they do exist, then you should verify that they are being used by running `explain` on the queries.  If they are being used, then you probably still have some sequential scans that could be sped up by more indexes.
