### ISSUE TITLE
Issue re-building pg_denormalized after removing $PGDATA

### ISSUE THREAD

**Issue by joeybodoia** [mikeizbicki/cmc-csci143#173]
For some reason my pg_denormalized container exits immediately after building. I didn't have this issue when I first built the container, but I am now encountering the issue after removing `$PGDATA` and rebuilding. Furthermore, this issue is only with `pg_denormalized` and not `pg_normalized`.

Running `docker ps -a` I see that the container for `pg_denormalized` exited immediately after being created.
```
CONTAINER ID   IMAGE                                          COMMAND                  CREATED          STATUS                      PORTS                                         NAMES
b53c0f80b763   twitter_postgres_indexes_pg_denormalized       "docker-entrypoint.s…"   14 seconds ago   Exited (2) 12 seconds ago                                                 twitter_postgres_indexes_pg_denormalized_1
e94802d3186c   twitter_postgres_indexes_pg_normalized_batch   "docker-entrypoint.s…"   14 seconds ago   Up 11 seconds               0.0.0.0:31076->5432/tcp, :::31076->5432/tcp   twitter_postgres_indexes_pg_normalized_batch_1
```

There were no issues presented when building, e.g., both containers were built successfully. Has anybody else run into a similar issue?

**Comment by mikeizbicki** [comment]
Most likely you have a bug in your sql that is causing it to crash.  You should run 
```
$ docker-compose logs pg_denormalized
```
to inspect exactly what is going wrong.

**Comment by joeybodoia** [comment]
Running `docker-compose logs pg_denormalized` I see the following:
```
pg_denormalized_1      | 
pg_denormalized_1      | PostgreSQL Database directory appears to contain a database; Skipping initialization
pg_denormalized_1      | 
pg_denormalized_1      | postgres: could not access the server configuration file "/var/lib/postgresql/data/postgresql.conf": No such file or directory
```
I'm not sure what would have removed this file. Is there an easy fix for this?

**Comment by ohorban** [comment]
@joeybodoia I am having a similar issue. The only useful information from running `$ docker-compose logs pg_denormalized` was
```
pg_denormalized_1      | initdb: error: directory "/var/lib/postgresql/data" exists but is not empty
pg_denormalized_1      | If you want to create a new database system, either remove or empty
pg_denormalized_1      | the directory "/var/lib/postgresql/data" or run initdb
pg_denormalized_1      | with an argument other than "/var/lib/postgresql/data".
```

However, deleting the postgres data by running `$ docker-compose exec pg_denormalized bash -c 'rm -rf $PGDATA'` did not solve the problem

**Comment by mikeizbicki** [comment]
@ohorban I have deleted your `$HOME/bigdata/pg_denormalized` folder for you.
