### ISSUE TITLE
Estimate for how long it takes to create denormalized indexes

### ISSUE THREAD

**Issue by DestrosCMC** [mikeizbicki/cmc-csci143#181]
I started creating all 4 of my denormalized indexes around 4 hours ago and one has successfully been created so far.
Is this the standard amount of time it takes?

Thanks.

**Comment by mikeizbicki** [comment]
At least one of my denormalized indexes took >1hr to create when there was no load on the lambda server, so this does not seem like an abnormal amount of time to me.  Depending on the exact indexes you are creating, the creation time on an unloaded lambda server could potentially be much higher.
