### ISSUE TITLE
channel 3: open failed: connect failed: Connection refused

### ISSUE THREAD

**Issue by joeybodoia** [mikeizbicki/cmc-csci143#185]
For the search engine assignment, I ran the `scripts/create_passwords.sh` script, modified the `docker-compose.override.yml` file, and successfully built the containers. Furthermore, I was successfully able to connect to the database by running 
```
$ docker-compose exec pg psql --user=novichenko
```
Next, I enabled ssh port forwarding by logging into the lambda server with the following:
```
ssh Joseph.Bodoia.21@134.173.191.241 -p 5055 -L 8080:localhost:5000
```
However, when I try to connect to the running flask app through localhost:8080, I'm met with the following error:
```
channel 3: open failed: connect failed: Connection refused
```
Running `docker ps`, I see that the development flask web app container is running (`search_engine_web`):
```
CONTAINER ID   IMAGE                      COMMAND                  CREATED         STATUS         PORTS                                       NAMES
62396714d749   search_engine_web          "python manage.py ru…"   3 seconds ago   Up 2 seconds   0.0.0.0:1076->5000/tcp, :::1076->5000/tcp   search_engine_web_1
00431018c43e   edoburu/pgbouncer:1.15.0   "/entrypoint.sh /usr…"   5 seconds ago   Up 3 seconds   5432/tcp                                    search_engine_db_1
2917c745f62f   search_engine_pg           "docker-entrypoint.s…"   6 seconds ago   Up 4 seconds   5432/tcp                                    search_engine_pg_1
```
Any advice for trying to debug this issue?

**Comment by mikeizbicki** [comment]
This error is generated by your ssh client when there is no service on the lambda server port (in your case 5000) every time you try to use the port forwarding.  Looking at your `docker ps` output, I can see that you have a port 5000 open inside of a container, but this is connected to port 1076 on the lambda server.  You need to adjust your `docker-compose.yml` and/or your ssh connection command to ensure that they are hitting the same port number.

**Comment by joeybodoia** [comment]
Great, thank you.
