### ISSUE TITLE
Error Building docker - Search Engine

### ISSUE THREAD

**Issue by afroCoderHanane** [mikeizbicki/cmc-csci143#187]
Hey Mike
I am having an error still with my build for the search engine:

```
ERROR: Could not install packages due to an OSError: [Errno 122] Disk quota exceeded

```

I  always ran `docker system prune -a `  and `docker volume prune` . I 've previously deleted the twitter indexes files and cleaned up my server
 when I ran docker ps -qa, nothing shows 
but the error that I am getting is :

```
The command '/bin/sh -c cd /tmp  && git clone https://github.com/mikeizbicki/pspacy  && cd pspacy  && sh install_dependencies.sh  && cp pspacy.py $APP_HOME/pspacy.py' returned a non-zero code: 1
Service 'web' failed to build : Build failed
````
I really don't know what I am getting wrong?

**Comment by mikeizbicki** [comment]
You can run 
```
$ du -hd1 $HOME
```
to see which folders in your home directory are using up your disk space, then delete those folders that you don't need.

**Comment by afroCoderHanane** [comment]
I deleted all the folder for the other assignments and it worked !! Thanks Mike
