### ISSUE TITLE
Mistakenly delete Bigdata folder

### ISSUE THREAD

**Issue by RuiluGao** [mikeizbicki/cmc-csci143#188]
Hi Mike,
I wrongly delete my bigdata folder on the server. Could you restore that for me? Thanks!

**Comment by mikeizbicki** [comment]
The bigdata folder is a [symlink](https://www.freecodecamp.org/news/symlink-tutorial-in-linux-how-to-create-and-remove-a-symbolic-link/) to the folder `/data/users_bigdata/$(whoami)`.  You can recreate it yourself with the command
```
$ ln -s /data/users_bigdata/$(whoami) $HOME/bigdata
```
