### ISSUE TITLE
Uploading Today's Review Session Video? Also a question.

### ISSUE THREAD

**Issue by dustin-lind** [mikeizbicki/cmc-csci143#195]
Hi Mike,

I was wondering if you are going to upload the recorded review session video from today? 

I am redoing the practice problems and I came across 55 in the T/F section. It asks:

> When it's possible to do both a hash join and a merge join, the merge join will always be faster

The answer key says `FALSE`, and I remember you saying something today about how sorting the data is expensive so that is why the merge join can be slower. But because it says "When it's possible", doesn't that imply that the data is already sorted. Because if the data were not sorted, then it would not be possible to do a merge join.

Best,

Dustin

**Comment by mikeizbicki** [comment]
> I was wondering if you are going to upload the recorded review session video from today?

Sorry, I thought I had recorded the session, but it seems zoom didn't record it.



>>  When it's possible to do both a hash join and a merge join, the merge join will always be faster
>
> The answer key says FALSE, and I remember you saying something today about how sorting the data is expensive so that is why the merge join can be slower. But because it says "When it's possible", doesn't that imply that the data is already sorted. Because if the data were not sorted, then it would not be possible to do a merge join.

That is correct.
