### ISSUE TITLE
Persisting error of disk quota & office hours 

### ISSUE THREAD

**Issue by afroCoderHanane** [mikeizbicki/cmc-csci143#206]
Did anyone one possibly got pass the disk quota exceeded when trying to insert crawl data into the db. It is through user `novichenko access denied`
after `disk quota exceeded ` and also Mike I wondered if it is still possible to see you in office anytime this week and next week since class ended ! Thank you .

**Comment by ohorban** [comment]
I am getting the same error
```
ERROR: Could not install packages due to an OSError: [Errno 122] Disk quota exceeded

The command '/bin/sh -c cd /tmp  && git clone https://github.com/mikeizbicki/pspacy  && cd pspacy  && sh install_dependencies.sh  && make USE_PGXS=1  && make USE_PGXS=1 install' returned a non-zero code: 1
warc=CC-MAIN-2013-48
Unable to find image 'novichenko/downloader_warc:latest' locally
docker: Error response from daemon: pull access denied for novichenko/downloader_warc, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
```

**Comment by axelahdritz** [comment]
I am having the same issue, but it is occurring even when tying to simply build the docker container. The error looks like this:

```
ERROR: Could not install packages due to an OSError: [Errno 122] Disk quota exceeded

The command '/bin/sh -c cd /tmp  && git clone https://github.com/mikeizbicki/pspacy  && cd pspacy  && sh install_dependencies.sh  && make USE_PGXS=1  && make USE_PGXS=1 install' returned a non-zero code: 1

ERROR: Service 'pg' failed to build : Build failed
```
I made sure to prune all of the volumes and delete all the information from previous twitter assignments.

**Comment by mikeizbicki** [comment]
It is definitely possible to complete the assignment in the allocated disk quota space.  Everyone who has shown me this problem so far has either:

1. not actually deleted all of their previous docker images/containers/volumes
1. had a problem with their `Dockerfile`s being incorrect

If those hints aren't enough to get it working, then we'll have to look at it in person.
