### ISSUE TITLE
Extension of Lulu's error failing /ngrams?query=trump

### ISSUE THREAD

**Issue by edwardwu11** [mikeizbicki/cmc-csci143#208]
Hi Mike and everyone else,

I tried running Lulu's solution of solving the submodule issue with the ```services/pg/data``` folder
```
$ git submodule init
$ git submodule update
```
and also checked to make sure the allsides folder wasn't empty which showed
```
$ du -h0 services/pg/data/allsides/      32K     services/pg/data/allsides/
```
However, after running ```docker-compose exec -T pg psql --user=novichenko < services/pg/sql/schema.sql```, I am still getting the same error
```
ERROR:  could not open file "/tmp/data/allsides/allsides.csv" for reading: No such file or directory
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.
```
If anyone has faced a similar issue and knows how to solve it please let me know. Thanks!

**Comment by mikeizbicki** [comment]
Running `git submodule update` caused you to change the contents of your `services/pg` folder, and so the image needs to be rebuilt.  My guess is that you did not run `docker-compose build` after running those commands?

**Comment by mikeizbicki** [comment]
> and also checked to make sure the allsides folder wasn't empty which showed
> 
> ```
> $ du -h0 services/pg/data/allsides/      32K     services/pg/data/allsides/
> ```

This is checking to see if the files exist on the lambda server.  The need to exist inside the `pg` container.  Rebuilding the image like I mentioned above will run a `COPY` command that moves them from the lambda server into the image.
