### ISSUE TITLE
Extra office hours Monday?

### ISSUE THREAD

**Issue by katiewu71** [mikeizbicki/cmc-csci143#215]
Hi Prof. Mike! I was wondering if you would be able to have extra office hours on Monday, during normal class time. Thank you!

**Comment by jzlilili** [comment]
I agree, I think having office hours in the morning would be more convenient for me.

**Comment by mikeizbicki** [comment]
Sorry, I have a handful of childcare obligations this morning that couldn't be moved and so am not available in the morning at all today.  I'll do my best to stay later during the normal office hours times, however, to ensure that everyone can get your questions answered.
