### ISSUE TITLE
Production Dockerfile error

### ISSUE THREAD

**Issue by gPlacide** [mikeizbicki/cmc-csci143#22]
On the _Production Dockerfile_ part of the tutorial I'm getting the following error 
`The command '/bin/sh -c addgroup -S app && adduser -S app -G app' returned a non-zero code: 1
ERROR: Service 'web' failed to build`

I'm getting the error when I build `docker-compose.prod.yml` and I'm almost certain that the error comes from `Dockerfile.prod` line 41 with
 ` # create the app user`
 `RUN addgroup -S app && adduser -S app -G app`

Is anyone else running into this error?

**Comment by cschulz21** [comment]
I think this could be solved by using Mike's `Dockerfile.prod` found here https://github.com/mikeizbicki/cmc-csci143/blob/2021spring/week_02/Dockerfile.prod

I think he addressed this in his announcement.
https://github.com/mikeizbicki/cmc-csci143/issues/20

**Comment by gPlacide** [comment]
> I think this could be solved by using Mike's `Dockerfile.prod` found here https://github.com/mikeizbicki/cmc-csci143/blob/2021spring/week_02/Dockerfile.prod
> 
> I think he addressed this in his announcement.
> #20
