### ISSUE TITLE
API Error

### ISSUE THREAD

**Issue by axelahdritz** [mikeizbicki/cmc-csci143#220]
Hey Mike, I have been having a lot of trouble just getting the docker containers for the search engine assignment up and running. There have been all sorts of password errors as explained in some of the issues, and then my build failed to load the data for some reason, and I've had to rebuild the docker container several times over. Now, I am blocked from building the container in the first place, with the error:

```
Step 6/17 : ADD https://api.github.com/repos/mikeizbicki/pspacy/git/refs/heads/master /tmp/pspacy.version
ADD failed: failed to GET https://api.github.com/repos/mikeizbicki/pspacy/git/refs/heads/master with status 403 Forbidden: {"message":"API rate limit exceeded for 134.173.191.241. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
ERROR: Service 'pg' failed to build : Build failed
```

I tried again a couple hours later and I still get the same error. Any help in getting the container up and running would really be a blessing as I have spent too much time trouble-shooting this!

**Comment by Bhargavaa1** [comment]
Hey Axel, I am receiving the same exact error and am also having trouble with getting the container up! Any help would be much appreciated.

**Comment by axelahdritz** [comment]
For me, it must have been a problem with the lambda server (too many requests). I just gave it couple more hours and it worked again (finally!)

**Comment by mikeizbicki** [comment]
Github allows only a certain number of requests (clones/pushes/pulls/etc) per timeperiod per ip address.  So if many people have recently performed those actions (e.g. by building a container which internally performs those actions), then github will block.  Waiting should fix the problem.
