### ISSUE TITLE
metahtml_rollup_host does not exist

### ISSUE THREAD

**Issue by katiewu71** [mikeizbicki/cmc-csci143#221]
When running: `select * from metahtml_rollup_host order by hostpath desc limit 100;`
I get the error: 
```
ERROR:  relation "metahtml_rollup_host" does not exist
```

Is this the expected output since we are no longer required to complete task 2b, or should the table still exist? Thanks!

**Comment by afroCoderHanane** [comment]
Use `metahtml_…._host2`. I submitted a for the correction and it was accepted yesterday.

**Comment by katiewu71** [comment]
Thank you! That worked. ☺️
