### ISSUE TITLE
Should we submit the last SQL query in Submission for Task 2b?

### ISSUE THREAD

**Issue by axelahdritz** [mikeizbicki/cmc-csci143#222]
Hey Mike!

I just wanted to confirm that since we did not need to complete task 2b anymore, that the last SQL query in the submission is no longer needed. When I run the query I get the error:

`ERROR:  relation "metahtml_rollup_host" does not exist`

Which makes sense if we did not complete 2b. Can I leave that query in the submission blank?

All the best,
Axel

**Comment by ohorban** [comment]
i think it's just the mixup with the table names. It should be `metahtml_rollup_host2`

**Comment by axelahdritz** [comment]
I did not see the previously closed issue regarding this point. Apologies! Thank you though!
