### ISSUE TITLE
Wardial Doctests Failing (Because Text is Expected)?

### ISSUE THREAD

**Issue by samcbogen** [mikeizbicki/cmc-csci143#223]
Hey Y'all (especially @mikeizbicki),

I am generating 5 doctest errors (screenshot attached), and I am not sure why. I am not sure why it is expecting text and not just the IP address. Did anyone encounter a similar error, and if so, how did you fix it?
<img width="656" alt="Screen Shot 2022-05-11 at 8 04 54 PM" src="https://user-images.githubusercontent.com/70249466/167986711-4cbbc764-4643-4bdf-a69d-a3ee488a11c0.png">

**Comment by mikeizbicki** [comment]
That additional text is not part of the test cases.  You've likely copy/pasted the code incorrectly, resulting in your docstrings being different from the docstrings in the original file.

PS. You should never post images of text to github, and should just copy/paste the text.  Images make it harder for google to search through error messages and it makes it harder for other people to help.

**Comment by samcbogen** [comment]
Won't post images again! Thank you for the help @mikeizbicki!
