### ISSUE TITLE
Zoom and lecture info

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/cmc-csci143#227]
All lectures will be recorded and broadcast live on zoom at the following url: https://cmc-its.zoom.us/j/3952597181. Lab sessions and office hours will not be recorded/broadcast.

**Comment by mariagerges** [comment]
Where can we find the link to the Youtube playlist for the class? Thank you!

**Comment by sybf-pro** [comment]
https://youtube.com/@mikeizbicki6115

**Comment by mikeizbicki** [comment]
Unfortunately, the first lecture video was corrupted by zoom due to my laptop running out of batteries.  Fortunately, the material we covered is the same as the material covered in the first lecture of CS46, and so you can watch that video instead.  It is posted at <https://www.youtube.com/playlist?list=PLSNWQVdrBwoax73YVijxAEUw29eD-zbSy>.

**Comment by mikeizbicki** [comment]
Today's lecture has been uploaded to youtube at <https://www.youtube.com/playlist?list=PLSNWQVdrBwoYGt2XIITaGHkaecHAYCGSG>.  All future lectures will be uploaded to the same playlist.

**Comment by mikeizbicki** [comment]
Today we covered how docker-compose relates to the flask-on-docker homework.  Unfortunately, the zoom recording got corrupted, and so it won't be uploaded to youtube.  Fortunately, I have a recording from last year that covers the same material.  You can find it at <https://www.youtube.com/watch?v=8wbNDEKMRmo&list=PLSNWQVdrBwoYKJ50dHmLCqd0hVdUZbWEv&index=11&t=105s>.  The recording covers the material in a slightly different way than we did in class today, but it actually covers a bit more edge cases than today's lecture did.

Again, there's lots of ways that you can accidentally go down the wrong track with this assignment, and so thing will be much easier if you all work together (in the approved spaces).
