### ISSUE TITLE
Question on Continuous Integration

### ISSUE THREAD

**Issue by sophiahuangg** [mikeizbicki/cmc-csci143#228]
Hi Mike, 

I'm getting this error when I try to check my "Actions" after pushing to Github. When I do `python3 --version` in terminal, it says I'm on `Python 3.6.9`. I was wondering if you have any suggestions on how to resolve this.

<img width="934" alt="Screen Shot 2023-01-22 at 7 28 49 PM" src="https://user-images.githubusercontent.com/89934020/213961211-0a9d162a-40c3-49d2-aa5b-64620ccec08b.png">

**Comment by mikeizbicki** [comment]
A number of students have had this problem, but I can't reproduce it on my own accounts, so I'm not sure what root causes is.

A simple fix, however, is to not run the tests on python 3.6 and only run them on the other python versions.  I've updated the `continuous-integration` repo to reflext this change.

Those of you who have already started the assignment can either:

1. Modify your version of the file `.github/workflows/tests.yaml` to look like [the current file on github](https://github.com/mikeizbicki/continuous-integration/blob/be4605d95b6fb83eb0a761c3a187b7fb10a9ee67/.github/workflows/tests.yml#L11).  (Only line 11 has been changed to remove the `3.6`.
2. Delete your fork on github and then redo the assignment from scratch.
