### ISSUE TITLE
Linus?

### ISSUE THREAD

**Issue by kanaluM** [mikeizbicki/cmc-csci143#238]
Why is **Linus Torvalds** a contributor in this repository? What is the story behind this?

<img width="409" alt="Screen Shot 2023-01-24 at 12 20 32 PM" src="https://user-images.githubusercontent.com/97998875/214418424-266fbf42-0648-437a-8c78-44dbbbecb12e.png">

**Comment by jbecker7** [comment]
+1 When is the Linus Ath Talk?

**Comment by mikeizbicki** [comment]
We'll talk about this in class at some point :)
