### ISSUE TITLE
Very last line of Production Dockerfile

### ISSUE THREAD

**Issue by amytam01** [mikeizbicki/cmc-csci143#24]
I'm running `docker-compose -f docker-compose.prod.yml exec web python manage.py create_db` and it's working up until step 9 with flake8. I tried the suggestions from Issue #20  but I'm still having problems. I'm getting `The command '/bin/sh -c flake8 --ignore=E501,F401 .' returned a non-zero code: 1
ERROR: Service 'web' failed to build`

![Screen Shot 2021-02-12 at 6 06 34 PM](https://user-images.githubusercontent.com/38165346/107838889-0c427480-6d5d-11eb-9404-589a292da9de.png)

 Any suggestions? Thanks :)

**Comment by cschulz21** [comment]
These look like best practice errors. I would go through and fix these in `manage.py` and `__init__.py`. It looks like you are just missing line spacing between functions and have an extra line in one file
