### ISSUE TITLE
How to access Twitter dataset?

### ISSUE THREAD

**Issue by BITEEE0308** [mikeizbicki/cmc-csci143#241]
For the lab this week, I forgot how to enter the "Twitter dataset" folder after I connected to lambda server.

I tried `cd 'Twitter dataset'`, `cd "Twitter dataset"`, and `cd Twitter\ dataset`, but none of them worked. 

The terminal said "no such file or directory". 

Glad if anyone can help!

**Comment by mikeizbicki** [comment]
Each of the commands that you listed are *relative* paths.  A relative path is any path that doesn't start with a `/`, and the working directory (which you don't specify) will be prepended to those paths to get the final *absolute* (or *full*) path that `cd` tries to change the directory to.

The absolute path that the twitter data set is located at is `/data/Twitter dataset`.  The leading `/` makes it an absolute path.  This path does not depend on your working directory.

**Comment by BITEEE0308** [comment]
Solved. Thank you!
