### ISSUE TITLE
Lab1: HUP signal && blocking HUP signal work in similar manner

### ISSUE THREAD

**Issue by jp-microsoft** [mikeizbicki/cmc-csci143#244]
Hello,

When I was doing lab1, I realized that exercises for HUP signal and blocking HUP signal worked in the same way. For both, the `./script.sh > output2` process did not stop running as soon as I closed the second session. 

However, this behavior was only expected when we used `nohup` to block HUP signal while running `./script.sh > output2 `command. I am not sure if it's the same for others, but let me know what might have caused it.

J.P.

**Comment by KaranGoel1** [comment]
To confirm, you closed the session in which the script was originally running, right? If you closed the other session, then the script will not stop. Hope that helps!

**Comment by jp-microsoft** [comment]
I closed the session where the script was running but it did not work as expected.

**Comment by mikeizbicki** [comment]
Sorry, I was planning on explaining in detail last class what was going on here, but I forgot.  We'll do that today in class.
