### ISSUE TITLE
Cannot tell that my script.sh file is running

### ISSUE THREAD

**Issue by KaranGoel1** [mikeizbicki/cmc-csci143#245]
<img width="533" alt="Screenshot 2023-01-28 at 2 45 16 PM" src="https://user-images.githubusercontent.com/81438058/215294566-09af975a-b951-4c36-9204-4b2d5dda38e8.png">

That's the output I get when my `script.sh` file is running, and I can't seem to figure out what the PID of it is. Does anyone know how I can read this?

**Comment by verynicocool** [comment]
I am having the same problem, I never see the `script.sh` file running when I run the `ps -ef | grep username` command. It has the exact same 5-line output whether `script.sh` is running in the other terminal or not.

**Comment by kevinm126** [comment]
I'm having the same problem. when i type the command `ps -ef | grep 'script.sh' ` i do see it and everyone else's

**Comment by mikeizbicki** [comment]
The left-most column of `ps -ef` is a username.  But the column is limited in space to only 8 characters.  So if your username is longer than 8 characters, it truncates it with a `+` symbol.  If you do a grep search for the first 7 characters of your username you should find all the expected results.

PS.  In the future, don't include screenshots of text in github.  Images aren't searchable by google or copy/pastable, so instead just copy/paste the output into a code block.
