### ISSUE TITLE
"docker build -t flask-tutorial:latest ." not working

### ISSUE THREAD

**Issue by BITEEE0308** [mikeizbicki/cmc-csci143#253]
When I ran the command `docker build -t flask-tutorial:latest  .`, I got the following long error message. Then, I tried the `pip install --upgrade pip` and the `pip install --upgrade setuptools` commands, but it still didn't work. 

<img width="966" alt="Screen Shot 2023-02-03 at 3 09 32 PM" src="https://user-images.githubusercontent.com/66191092/216727819-8f800fa4-3bcb-4faf-aae3-729f33158c53.png">

However, when I checked my version of pip, it has been already updated. It is very appreciated if anyone can offer help!

**Comment by hfmandell** [comment]
+1

**Comment by mikeizbicki** [comment]
This is expected behavior in the sense that I intentionally gave you all a tutorial that was broken.  I've updated the instructions with some more clarity about how to go about fixing the problem:

> Finally, there's a handful of errors that you'll get when you build the project. You'll find that fixing these errors only takes a very small change to the project files, but figuring out exactly what this change is will be quite difficult. The fundamental problem is that various libraries/packages have introduced breaking changes since the author of the tutorial wrote the tutorial. The easiest way to figure out how to get the right versions is to open up a working container with the `docker run` command, then manually try installing all the different versions of the libraries until you get something that successfully creates the webpage. Once you've figured out the correct sequence of commands, then you should modify the `Dockerfile` to reflect these new commands.
