### ISSUE TITLE
"docker run -d -p $UID:$UID flask-tutorial": not working 

### ISSUE THREAD

**Issue by BITEEE0308** [mikeizbicki/cmc-csci143#254]
I changed something in Dockerfile and the docker build command seems working now. However, I'm getting the error message below when I'm trying to run `docker run -d -p $UID:$UID flask-tutorial`, `docker run -d -p $UID:5000 flask-tutorial`, or `docker run -d -p 5000:$UID flask-tutorial`. 

<img width="657" alt="Screen Shot 2023-02-04 at 1 38 18 PM" src="https://user-images.githubusercontent.com/66191092/216790616-7cdb3922-a45d-44fd-9c77-064c378049b7.png">

It is very appreciated if anyone can offer help!

**Comment by KaranGoel1** [comment]
I'm having the same problem. I've spent hours looking through executable files and environment variables to try and change the path, but haven't found a solution yet. I tried the suggested solution from a previous issue, but that did not work for me. Hopefully someone can shed some light!

**Comment by kevinm126** [comment]
+1

**Comment by ifreer23** [comment]
+1
