### ISSUE TITLE
Can't access http://localhost:8080/ with error "channel 3: open failed: connect failed: Connection refused"

### ISSUE THREAD

**Issue by Aser-Abdelfatah** [mikeizbicki/cmc-csci143#258]
In lab 2, I used Windows Power Shell to run the command (changed username to my actual username)
```
$ ssh username@134.173.191.241 -p 5055 -L 8080:localhost:5000
```
I can login to the lambda server, but I can't access http://localhost:8080/. I tried multiple browsers, but none is working. Also, I receive the error "channel 3: open failed: connect failed: Connection refused", and the error gets repeated many times in the SSH client.

**Comment by livrenfro** [comment]
^

**Comment by mariagerges** [comment]
Can you let me know how you solved this?
