### ISSUE TITLE
Nginx Docker compose error

### ISSUE THREAD

**Issue by amytam01** [mikeizbicki/cmc-csci143#26]
Hi there again, I'm facing an error as usual trying docker compose. My error happens towards one of the last steps of Nginx when I try to run `docker-compose -f docker-compose.prod.yml exec web python manage.py create_db`.

The error I get is 
`ERROR: for e5c28d72220d_flask-on-docker_nginx_1  Cannot start service nginx: driver failed programming external connectivity on endpoint flask-on-docker_nginx_1 (6c37d4f69ec4ff84058a1945ee0a63df6d71c7d8d9d57bff9eb55531d13c8d6f): Error starting userland proxy: error while calling PortManager.AddPort(): listen tcp 0.0.0.0:1337: bind: address already in use`

and

`ERROR: for nginx  Cannot start service nginx: driver failed programming external connectivity on endpoint flask-on-docker_nginx_1 (6c37d4f69ec4ff84058a1945ee0a63df6d71c7d8d9d57bff9eb55531d13c8d6f): Error starting userland proxy: error while calling PortManager.AddPort(): listen tcp 0.0.0.0:1337: bind: address already in use
ERROR: Encountered errors while bringing up the project.`

Thanks for everything! 
![Screen Shot 2021-02-12 at 6 42 10 PM](https://user-images.githubusercontent.com/38165346/107839633-04d19a00-6d62-11eb-8834-879da559e0a1.png)

**Comment by mikeizbicki** [comment]
The key line is
```
listen tcp 0.0.0.0:1337: bind: address already in use
```
this means that you are trying to start a service, but a service is already using that port.  (A likely cause is that the dev version is running when you try to run the prod version.)  Make sure that you shutdown all of your services before starting, and if that doesn't work than double check the port configurations.

PS. Your error messages are hard to read because you are using single backticks instead of triple backticks.

**Comment by amytam01** [comment]
So you were right, my dev version was still running. Now I'm able to run the prod version but am still facing errors.

```channel 3: open failed: connect failed: Connection refused```

![Screen Shot 2021-02-13 at 8 20 37 AM](https://user-images.githubusercontent.com/38165346/107854959-5adf2580-6dd4-11eb-9e53-013baa3baf78.png)

Thanks again! :D

**Comment by mikeizbicki** [comment]
It looks like the containers are running correctly now, so the only issue left is the port settings.  Make sure that the ports are correct in your `docker-compose.prod.yml` file, and not just the `docker-compose.yml` file.

**Comment by amytam01** [comment]
I checked both my `docker-compose.prod.yml` file and my `docker-compose.yml` file (plus the other files). But they all seem correct to me based off the instructions in the tutorial. If you could point out something that I may just not be seeing I'd super appreciate it (note: I'm still in the nginx section of tutorial and my UID is 1137):

![Screen Shot 2021-02-13 at 2 06 17 PM](https://user-images.githubusercontent.com/38165346/107862841-a5789600-6e04-11eb-8d05-0d6cd747c150.png)

![Screen Shot 2021-02-13 at 2 06 55 PM](https://user-images.githubusercontent.com/38165346/107862847-bcb78380-6e04-11eb-80a5-405deb26458a.png)

**Comment by mikeizbicki** [comment]
Hmm... all those settings look good to me.  I also just checked your port forwarding settings for your current login, and those look good too.

One possibility is that the nginx server is not setup correctly.  I see from your `docker ps` that it is running, but it's possible that your settings file has it listening on the wrong ports or connecting to the web server on the wrong ports.

If looking at the settings file doesn't help, I'm probably not going to be any help without a zoom call.  I'd be able to look at it Monday after class.

**Comment by afzal-p** [comment]
I reverted the step where `expose ` replaces `ports` and was able to finish the tutorial

**Comment by amytam01** [comment]
Did something along the lines of Afzal's suggestion and was able to complete the tutorial :)
