### ISSUE TITLE
Question about Quiz

### ISSUE THREAD

**Issue by emjuliet** [mikeizbicki/cmc-csci143#265]
HI,

I just wanted to confirm a syntax thing. When using "" in if statements such as in this example:

`cat > quiz.sh <<'EOF'
foo='hello'
if [ "$foo" = "hello" ] 
     touch if`

This should return if right? I just wanted to clarify because I know the quotations are needed to match something like hello world, but I was wondering if the quotations affect when it is just one word in $foo .

**Comment by mikeizbicki** [comment]
What you have written has errors in it.  Probably you meant to use a triple backtick code block instead of a single backtick inline code.  If you fix this, then I can answer the question.
