### ISSUE TITLE
OSError: [Errno 98] Address already in use

### ISSUE THREAD

**Issue by emjuliet** [mikeizbicki/cmc-csci143#267]
Hi,
When I try to run the `python manage.py run` command, I get this error:

OSError: [Errno 98] Address already in use

How do I fix this? Thank you

**Comment by emjuliet** [comment]
I am getting a similar error when I run `docker-compose up -d` as well

**Comment by ifreer23** [comment]
+1

**Comment by mariagerges** [comment]
+1
