### ISSUE TITLE
Collaboration Thread

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/cmc-csci143#268]
This issue amends the collaboration policy to allow more opportunities for collaboration.  In particular, you can reply to this issue with a time/location that you would like to work as a group.  You will be automatically approved for collaboration if:

1. the reply is posted at least 4 hours in advance of the event, and
2. the location is "reasonably" accessible by everyone (e.g. the HUB, any dining hall, or a study room in the library).

My goal is for everyone in the class to have access to the collaboration opportunities, and for you all to collaborate with people outside of just your small friend groups.

**Comment by T2R2N2A2M2M** [comment]
Location: Underneath the CMC's Cube
Time: Sunday Feb 12, 2023: 1:30 pm.
