### ISSUE TITLE
User Tables: hello_flask_dev=# \dt Did not find any relations.

### ISSUE THREAD

**Issue by livrenfro** [mikeizbicki/cmc-csci143#271]
Hi Mike,

When checking that the `users` table was created using the following command:

```
docker-compose exec db psql --username=hello_flask --dbname=hello_flask_dev
```

The table seems to have built: 

```
/home/Olivia.Renfro.23/.local/lib/python3.6/site-packages/paramiko/transport.py:32: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography (40.0) will be the last to support Python 3.6.
  from cryptography.hazmat.backends import default_backend
psql (13.10)
Type "help" for help.

hello_flask_dev=# \l
                                        List of databases
      Name       |    Owner    | Encoding |  Collate   |   Ctype    |      Access privileges      
-----------------+-------------+----------+------------+------------+-----------------------------
 hello_flask_dev | hello_flask | UTF8     | en_US.utf8 | en_US.utf8 | 
 postgres        | hello_flask | UTF8     | en_US.utf8 | en_US.utf8 | 
 template0       | hello_flask | UTF8     | en_US.utf8 | en_US.utf8 | =c/hello_flask             +
                 |             |          |            |            | hello_flask=CTc/hello_flask
 template1       | hello_flask | UTF8     | en_US.utf8 | en_US.utf8 | =c/hello_flask             +
                 |             |          |            |            | hello_flask=CTc/hello_flask
(4 rows)
```

And I can connect to the database: 

```
hello_flask_dev=# \c hello_flask_dev
You are now connected to database "hello_flask_dev" as user "hello_flask".
```

But when I check `\dt`, it does not find any _relations_:

```
hello_flask_dev=# \dt
Did not find any relations.
```

Before editing the files to build the table, the container was running properly but now the connection is refusing. Please let me know if you have any idea about what could have gone wrong!

**Comment by BITEEE0308** [comment]
+1

**Comment by livrenfro** [comment]
Hello, it is still displaying the same result for `\dt` but I was able to continue with the assignment for the time being. Can I continue to ignore this or will it become a problem? Thanks!

**Comment by mariagerges** [comment]
I have the exact same problem

**Comment by mikeizbicki** [comment]
The `web` service is responsible for creating these tables when it is brought up.  Probably there is an error in this service somewhere.  The instructions at this point state:

> Again, if the container fails to start, check for errors in the logs via `docker-compose -f docker-compose.prod.yml logs -f`.

The output of this command would tell us exactly what the error is.

**Comment by verynicocool** [comment]
Are we supposed to have a `docker-compose.prod.yml` file at this point in the tutorial. I'm getting the same no relations problem but I can't check for errors since I don't have the `.prod` file.

**Comment by jp-microsoft** [comment]
If you are still having issues and the logs show that you need SQLAlchemy library, add this line to your requirements.txt file.`Flask-SQLAlchemy==3.0.2`
