### ISSUE TITLE
Docker-Compose Build permission denied

### ISSUE THREAD

**Issue by samujala** [mikeizbicki/cmc-csci143#272]
When I try to run the `docker-compose build` command in my root project folder I get the error: 

`-bash: /usr/bin/docker-compose: Permission denied`

I tried to vim into this file and saw it was a readonly file, but not sure why I am getting this error. Thanks.

**Comment by verynicocool** [comment]
Could I ask what was the fix to this error?

**Comment by laurenleadbetter** [comment]
+1

**Comment by Aser-Abdelfatah** [comment]
+1
