### ISSUE TITLE
Postgres Problems

### ISSUE THREAD

**Issue by emjuliet** [mikeizbicki/cmc-csci143#273]
Hi!

When running `docker-compose exec web python manage.py seed_db`

I get this error:
AttributeError: module 'sqlalchemy' has no attribute '__all__'. Did you mean: '__file__'?

I tried uninstalling installing older version of sclalchemy but I am still getting the same error. 
After creating the users tables, the local host:5000 link also stopped working, saying the connection was refused. I was wondering if you had any other tips to get past these two issues. Thank you so much!

**Comment by ifreer23** [comment]
+1

**Comment by sybf-pro** [comment]
If you change the version of flask_sqlachemy to 3.0.2 from the requirements.txt, that should fix it.

**Comment by ifreer23** [comment]
That worked thank you!

> If you change the version of flask_sqlachemy to 3.0.2 from the requirements.txt, that should fix it.

**Comment by emjuliet** [comment]
Thanks Sybel!
