### ISSUE TITLE
docker cryptography error

### ISSUE THREAD

**Issue by verynicocool** [mikeizbicki/cmc-csci143#274]
I am currently getting the following error:

```
$ docker-compose up -d --build
/home/nvillalba/.local/lib/python3.6/site-packages/paramiko/transport.py:32: CryptographyDeprecationWarning: Python 3.6 is 
no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of 
cryptography (40.0) will be the last to support Python 3.6.
```

I know we fixed this problem in class by going into some file and making the argument to something an empty string. I have had to reinstall docker since then and I cannot remember in what file we went into in order to make that change.

Does anyone remember?

**Comment by kanaluM** [comment]
This message is a just a warning (`CryptographyDeprecationWarning`) so it should not cause any problems with running the code. I think the file change you are referring to was a fix for something else but I can't remember what it was for...
