### ISSUE TITLE
question mark pattern match question 

### ISSUE THREAD

**Issue by kevinm126** [mikeizbicki/cmc-csci143#275]
Hi all,

I wanted to ask a question regarding the question mark pattern match character. In the notes it says that the question mark matches 0 or 1 character. The following is number 7 on the practice quiz
```
$ cd; rm -rf quiz; mkdir quiz; cd quiz
$ touch "hello world"
$ touch "hola mundo"
$ touch "salve munde"
$ rm *d?
$ ls | wc -l
```
This outputs 1 and the command seems not to match "hello world". Can anyone clarify?

**Comment by mikeizbicki** [comment]
The POSIX shell `?` matches exactly one character; the regex `?` matches zero or one character.  There was previously a typo in the practice problems, but I've since fixed it.
