### ISSUE TITLE
shell script run_maps.py

### ISSUE THREAD

**Issue by emjuliet** [mikeizbicki/cmc-csci143#279]
Hi,

I am trying to run the shell script to run maps.py for the Twitter Coronavirus hw, but I am getting an error saying file not found for 2020 tweets.

This is my code:
```   
     for file in /data/Twitter\ dataset/; do
          ./src/map.py --input_path=/data/Twitter\ dataset/geoTwitter20*
     done  
```

Is there something wrong with my glob or my path?

**Comment by kanaluM** [comment]
What exactly was the error?

I would guess that the glob in the body of the for-loop is causing an issue. The `--input_path` parameter should only take in one specific file to analyze, but the glob might be trying to expand to all files or something

I might suggest using the `$file` variable you define in the for-loop as the `--input_path`

**Comment by emjuliet** [comment]
That ran! Thank you so much. But now I am getting this error for a lot of files:

map.py: error: unrecognized arguments: dataset/geoTwitter20-03-17.zip

**Comment by kanaluM** [comment]
Maybe the space character in `/data/Twitter\ dataset/geoTwitter20*` is causing things to be parsed incorrectly in your variable expansion. Try using double quotes around variable names to make sure that spaces are not messing things up
