### ISSUE TITLE
docker-compose credential error

### ISSUE THREAD

**Issue by KaranGoel1** [mikeizbicki/cmc-csci143#282]
I've been trying to run the flask-on-docker sanity checks and I keep getting this error after running `docker-compose up -d`:

```
docker.credentials.errors.InitializationError: docker-credential-secretservice  not installed or not available in PATH
```

I had altered the `~/.docker/config.json` file due to a previous error I was getting, which caused this error. So I had changed it back to what it was before but the error remains. 

The previous error was `Cannot autolaunch D-Bus without X11 $DISPLAY`, and the recommended fix was to make the `credsStore` key in the `~/.docker/config.json` file have an empty string as its value. I deleted the "secretservice" string, which caused the new error. Thus, I wrote it back in, but the error doesn't go away. Any help would be much appreciated!

**Comment by kevinm126** [comment]
If you have tried uninstalling and reinstalling docker already maybe try the following commands
```
systemctl --user stop docker
systemctl --user daemon-reload
systemctl --user start docker
```
this may work or could also do nothing at all please let me know

**Comment by jaymaliye** [comment]
+1

I received the same error. I went ahead and checked the logs for this error and received an output saying:

`web_1  | Traceback (most recent call last):` 
`web_1  |   File "/usr/src/app/manage.py", line 3, in <module>`
`web_1  |     from project import app`
`web_1  |   File "/usr/src/app/project/__init__.py", line 2, in <module>`
`web_1  |     from flask_sqlalchemy import SQLAlchemy`
`web_1  | ModuleNotFoundError: No module named 'flask_sqlalchemy'`

When I run `docker-compose build`, it says that flask_sqlalchemy has been installed. But when manage.py tries to run, it barfs the error shown above. Having a lot of trouble with this. I have tried the following solutions:

1. Changing the version of flask_sqlalchemy to 3.0.2 and 2.5.0
2. Entering `RUN pip install -U Flask-SQLAlchemy` explicitly in the Dockerfile
3. Tried different versions of postgres-alpine
4. Tried different versions of python3

Unfortunately none of these solutions seem to be working. I always receive the error posed by @KaranGoel1 and the logs always show the ModuleNotFoundError. 

Any help would be much appreciated!

**Comment by jaymaliye** [comment]
> 

Hi @kevinm126. Thanks for sharing that! I ran those commands, but I'm still getting the same error.

Now when I try to run `docker-compose logs -f` or `docker-compose logs`, the output hangs at the line
`Attaching to`

**Comment by jaymaliye** [comment]
> If you have tried uninstalling and reinstalling docker already maybe try the following commands
> 
> ```
> systemctl --user stop docker
> systemctl --user daemon-reload
> systemctl --user start docker
> ```
> 
> this may work or could also do nothing at all please let me know

Do you know the commands to uninstall and reinstall docker?

**Comment by KaranGoel1** [comment]
> > If you have tried uninstalling and reinstalling docker already maybe try the following commands
> > ```
> > systemctl --user stop docker
> > systemctl --user daemon-reload
> > systemctl --user start docker
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > this may work or could also do nothing at all please let me know
> 
> Do you know the commands to uninstall and reinstall docker?

Use the following link: [Docker install](https://docs.docker.com/engine/security/rootless/#install)

Install the version without packages

**Comment by jaymaliye** [comment]
> Docker install

Got it! And what command to run to uninstall it? Sorry for asking so many questions, I've been stuck on this for a while and want to make sure I'm doing it right! Thanks.

**Comment by KaranGoel1** [comment]
> > Docker install
> 
> Got it! And what command to run to uninstall it? Sorry for asking so many questions, I've been stuck on this for a while and want to make sure I'm doing it right! Thanks.

If you scroll down, you should be able to see uninstallation instructions

**Comment by KaranGoel1** [comment]
I had a typo, so I have fixed the new error. I still have the following error:

```
docker.errors.DockerException: Credentials store error: StoreError('Credentials store
docker-credential-secretservice exited with "Cannot autolaunch D-Bus without X11 $DISPLAY".',)
```

Any help would be appreciated!

**Comment by KaranGoel1** [comment]
@jaymaliye were you able to solve the problem?

**Comment by jaymaliye** [comment]
@KaranGoel1 I tried reinstalling docker but it gave me the same error. I then proceeded to wipe my lamdba server and set it up from scratch, but now every time I try to build it says permission denied. 

Not sure how to move forward from here so I think I'm gonna go for office hours.
