### ISSUE TITLE
pagila-hw passing all tests but failing on GitHub

### ISSUE THREAD

**Issue by jaymaliye** [mikeizbicki/cmc-csci143#284]
All the test cases on the pagila-hw passed. But when I push to GitHub, it says failed. 

When I checked the logs, all 20 tests pass, but it says that there is an error with docker. The message is:

`Error: Process completed with exit code 2.`

I changed the `README.md` file so that the test case image points to my forked repo by changing mikeizibiki to jaymaliye. I am not sure what else to do and would appreciate any help!

**Comment by kushpetal** [comment]
^ having the same issue

**Comment by nessakiani** [comment]
^ I'm also having the same problem

**Comment by danimonz** [comment]
^ I had the same problem

**Comment by mikeizbicki** [comment]
There is almost certainly a problem with your order by clause, and you can check the output of github actions to verify this.

Again, ordering is non-deterministic in SQL unless explicitly specified.  This can cause the ordering of the lambda server and the github actions servers to be arbitrarily different unless you explicitly tell them to be the same.  After the midterm, we'll talk about why this non-deterministic ordering improves algorithmic performance.
