### ISSUE TITLE
I need help to find the sql_quiz directory that was used in Monday's class (Feb 20)

### ISSUE THREAD

**Issue by jp-microsoft** [mikeizbicki/cmc-csci143#294]
Hello,

I am trying to find the sql-quiz directory that prof used in Monday's class. I found [sql_quiz](https://github.com/mikeizbicki/sql_quiz/tree/c4206e0d6a0593597f3c5ff6657c1431b64e3176) which doesn't have any .sql files I need. If anyone knows why there are no these files on GitHub or how I can get them, please let me know.

**Comment by tennisoctocat** [comment]
This [sql_quiz link](https://github.com/mikeizbicki/sql_quiz) should work! I think you were originally only looking at the initial commit.
