### ISSUE TITLE
Twitter homework bar graphs not displaying Korean hashtag

### ISSUE THREAD

**Issue by samchotzen** [mikeizbicki/cmc-csci143#295]
I'm working on the Twitter homework and the bar graphs aren't displaying the Korean characters, but are instead displaying empty boxes where the characters should be. Can we receive extra credit if we fix this problem?

**Comment by mikeizbicki** [comment]
Sure :)  There will be no penalty applied if your graphs don't display the non-ASCII characters, but if you figure out how to install the font for these characters and display them correctly I'll give you +1 point extra credit.
