### ISSUE TITLE
Lecture recordings

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/cmc-csci143#3]
As mentioned today in class, all lectures will be recorded so you can watch them asynchronously.  I'll be posting the recordings to a youtube playlist at:

https://www.youtube.com/playlist?list=PLSNWQVdrBwoYN0AqeD8iJDZoDiJE6IF6g

The first video has been uploaded.

**Comment by mikeizbicki** [comment]
Today (2021-03-17) zoom crashed at the end of lecture, and so the recording file is corrupted.  This poses a particular problem for those of you taking the course asynchronously and are dependent on the video recordings.  To mitigate this problem, I will use the lab time this week to redo the session.  I will record that session and upload that video.

I'll also take the opportunity to highlight a fundamental problem with zoom's architecture: They invented their own proprietary format for video recording.  This format has no built-in fault tolerance, and so a zoom crash renders the entire file corrupted.  If they were using an ACID-compliant database (e.g. postgres or sqlite), they would be guaranteed not to have this problem.  Databases are not traditionally used for storing videos because they have a fair bit of overhead, but standard video formats like MPEG have built-in fault tolerance.  If they had been using one of these standrd formats instead of their own proprietary format, then a zoom crash would not cause the loss of the video.

The takeaway message is that you should never invent your own file formats.  Always use standard media file formats for video/images, and use databases for everything else.  If you do this, your program will be guaranteed to not lose data even if it crashes.

**Comment by mikeizbicki** [comment]
The re-recorded lecture for Wednesday (2021-03-17) has now been uploaded to youtube.

**Comment by cschulz21** [comment]
The lecture recording from 2021-04-07 "more indexes, aggregation strategies" is posted to your YouTube channel, but is not in the big data playlist linked above.

**Comment by mikeizbicki** [comment]
@cschulz21 Whoops, looks like I forgot to check the box when uploading it.  It's fixed now.  Thanks for pointing that out.

**Comment by CurtisSalinger** [comment]
Hi Mike, I was also wondering if you'd perhaps forgotten to post the 4/21/21 lecture to Youtube? I do not see it on the channel. Thanks!

**Comment by mikeizbicki** [comment]
It looks like it's uploaded fine, with the exception that I accidentally labelled it `2020-04-21` rather than `2021-04-21`.  The following link goes directly to it: https://www.youtube.com/watch?v=zIQ18u7Aq4w&list=PLSNWQVdrBwoYN0AqeD8iJDZoDiJE6IF6g&index=23

**Comment by CurtisSalinger** [comment]
I see, thank you!
