### ISSUE TITLE
Some data files are missing from the server: there is only one file in /data-fast/twitter\ 2020 folder

### ISSUE THREAD

**Issue by jp-microsoft** [mikeizbicki/cmc-csci143#302]
Hello,

I am trying to run my code but most of the data files are missing in the `/data-fast/twitter\ 2020` folder.  When I run the following command:
`cd /data-fast/twitter\ 2020; ls;`
I only get one file for April, 01, 2020.
`geoTwitter20-04-01.zip`

Where could I find all the files?

**Comment by JSanders24** [comment]
I have this same result. It results in having a very limited number of the tweets show up in the graph. Would love some help on this problem too. Are we responsible for grabbing the /data-fast/twitter files?

**Comment by jp-microsoft** [comment]
We have to use `/data/Twitter\ dataset/` directory

**Comment by JSanders24** [comment]
Is that referring to the run_maps.sh file? Because that's the directory I use there which still results in missing tweets

**Comment by jp-microsoft** [comment]
Are you getting an error? Or how many files are you getting?
