### ISSUE TITLE
Earning extra points past the extra credit assignments

### ISSUE THREAD

**Issue by KaranGoel1** [mikeizbicki/cmc-csci143#304]
Hi Mike,

Can we earn more points by watching/reading more of the content in the culture caveat task past 4 points, or through any other means? I'd like to earn more extra credit points than what the extra credit tasks seem to allow.

**Comment by mikeizbicki** [comment]
I'm open to awarding more extra credit, but I don't have any concrete ideas about how to do so.  If you have suggestions, I'd be happy to consider them.  (They'd have to be rather "intense" tasks, however, for me to award extra credit for them.)
