### ISSUE TITLE
No Issue for Caveat Tasks

### ISSUE THREAD

**Issue by tennisoctocat** [mikeizbicki/cmc-csci143#305]
Hi Mike! 

It appears that there is no open issue for CS 143 caveat tasks. Should we post to [last year's issue](https://github.com/mikeizbicki/cmc-csci143/issues/84) or [CS 43's issue](https://github.com/mikeizbicki/cmc-csci046/issues/450)? Or will a new one be created? Thanks!

**Comment by mikeizbicki** [comment]
Eeek... it's now posted at https://github.com/mikeizbicki/cmc-csci143/issues/307.  Thanks for letting me know!

(There'a no need to repost in this issue for people who've already posted something in the CS46 issue.)
