### ISSUE TITLE
error: the following arguments are required: --db, --inputs

### ISSUE THREAD

**Issue by BITEEE0308** [mikeizbicki/cmc-csci143#308]
Hi Mike!

When I updated the py file and ran `python3 load_tweets.py`, it threw the error that `error: the following arguments are required: --db, --inputs`. 
When I rechecked the tables, data was not inserted successfully. Is there any way I can solve it?

Thank you!

**Comment by kanaluM** [comment]
Those are command line arguments for the main function in `load_tweets.py` 
When running the file, you have to specify where to insert the data (`db`) and what data to insert (`inputs`)
I think the code you write in `load_tweets.sh` should probably look something like
```
python3 load_tweets.py --db=SOMETHING --inputs=SOMETHING
```
