### ISSUE TITLE
Grades on Sakai & Friday Lab

### ISSUE THREAD

**Issue by mariagerges** [mikeizbicki/cmc-csci143#309]
Hi Mike, I hope you're having a good day! 

For some reason, the grades for each specific assignment are not showing on Sakai. It's just showing the total grade for the course. Can you please fix that?

Also, Will we have lab this Friday?

Thank you so much!

**Comment by mikeizbicki** [comment]
> For some reason, the grades for each specific assignment are not showing on Sakai. It's just showing the total grade for the course. Can you please fix that?

Whoops, not sure how that setting got changed.  It should be fixed now.

> Also, Will we have lab this Friday?

No class today.  I will be in my office, however, if anyone has questions/would like to meet.
