### ISSUE TITLE
changing ports not working

### ISSUE THREAD

**Issue by KaranGoel1** [mikeizbicki/cmc-csci143#312]
I have changed the left side number many times and find it incredibly improbable that all the random numbers I've tried are already in use. I'm not being able to get my docker to work. Anyone know other ways to fix this, or do I have to just keep trying new numbers? Is my `docker-compose exec` command not using the updated values for some reason? Thanks!

**Comment by jp-microsoft** [comment]
Try two different numbers: one for each service. Also, you have to `docker-compose up -d --build` every time you update the `docker-compose.yml` file.
