### ISSUE TITLE
Class cancelled today

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/cmc-csci143#314]
I'm cancelling class today because I've lost my voice and can't speak at all.  Therefore:

1. The quiz that we would have had today will be postponed until next week.
2. As soon as I'm able, I will create a video explaining what to do for your next assignment and post the assignment.
3. The due date for the assignment will be extended until Thursday next week (6 Apr).
4. We won't have class this Friday.

I'm sorry for the inconvenience.

**Comment by mikeizbicki** [comment]
I've uploaded the video for the missed class at <https://www.youtube.com/watch?v=EJaOmjQswaU>.

The video covers the next homework, which you can find at: <https://github.com/mikeizbicki/twitter_postgres_parallel>.

I'll go ahead and extend the due date for the assignment even further to Tuesday, April 11 so that you'll have plenty of time to complete it.

**Comment by laurenleadbetter** [comment]
Will the transactions quiz be in class today or Wednesday?

**Comment by mikeizbicki** [comment]
The quiz is Wednesday.  (Sorry for the lack of clarity above.)
