### ISSUE TITLE
OperationalError

### ISSUE THREAD

**Issue by BITEEE0308** [mikeizbicki/cmc-csci143#317]
Hi!
For the normalized_batch insertion, I modified the `load_tweets_batch.py`, `load_tweets_parallel.sh`, and `services/pg_normalized_batch/schema.sql`. When I run `sh load_tweets_parallel.sh`, the denormalized insertion and unbatched normalized insertion are correct and passed all tests.

However, the batched normalized insertion is throwing an error 
`sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 12987 failed: Connection refused
Is the server running on that host and accepting TCP/IP connections?`
The port numbers are correct and I don't think that's the problem.

Does anyone know any potential solution? That will be really appreciated!!

**Comment by kanaluM** [comment]
I also got this error after editing the `services/pg_normalized_batch/schema.sql` file. It was because my file had errors in it. After fixing the errors, the code ran successfully
