### ISSUE TITLE
Workflow file causing error

### ISSUE THREAD

**Issue by KaranGoel1** [mikeizbicki/cmc-csci143#318]
Hi,

My code for sequential loading has been failing the actions but passing all the tests. I believe the error that it runs into is caused by the `load_tweets_sequential.sh` file being executed using an `sh` command instead of a `bash` command in the workflow `.yml` files. Are we allowed to edit the workflow files, or is there another way to get around this issue? Thanks!

**Comment by mikeizbicki** [comment]
Eeek... you're right!  I added the `time` command in front of the for loop, which is bash only syntax, and didn't think about how this might affect the test cases.

It's fine to modify github actions and replace the `sh` with `bash` to fix this problem.

**Comment by BITEEE0308** [comment]
Hi,

I changed all the files in the workflow by changing `sh xxx.sh` to `bash xxx.sh`. Also, I changed the `#!/bin/sh` in my `load_tweets_parallel.sh` and `load_tweets_sequential.sh` files into `#!/bin/bash`. When I ran the 2 .sh files on the server, everything works fine with no error and the test cases were passed. However, I still cannot pass the tests on GitHub. 

Thank you!

**Comment by snarayan23** [comment]
+1 having the same problem ^

**Comment by tennisoctocat** [comment]
What is the error message that you're getting / what do the logs say? I had the same behavior (i.e. the tests passed on the lambda server but not on github) due to an `InvalidRequestError` in my `load_tweets.py` file. If you have the same error, I solved it using the fix from [this issue](https://github.com/mikeizbicki/cmc-csci143/issues/311).

**Comment by BITEEE0308** [comment]
Hi! 
Thank you! I added `connection.commit()` in `load_tweets.py`. When I commented out the batch insertion in the 2 `.sh` files, the other 4 cases passed GitHub tests. 

However, when I 1. added `connection.commit()` in `load_tweets_batch.py` or 2. removed `with connection.begin() as trans:`, the github actions still failed. 

The error for the first change is `sqlalchemy.exc.InvalidRequestError: Can't operate on closed transaction inside context manager.  Please complete the context manager before emitting further commands.`. 

The error for the second change is `Error: The operation was canceled`. 

Does anyone have the same situation or know how to solve it? The test cases are running fine and correct on my server if I did not make these changes.

**Comment by tennisoctocat** [comment]
For `load_tweets_batch.py`, removing the `with connection.begin() as trans:` in the `_insert_tweets ` function and leaving everything else the same worked for me. But if that's what you did, perhaps you're getting a different error than the one I had
