### ISSUE TITLE
An extra credit game

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/cmc-csci143#319]
<https://deadlockempire.github.io/> is a game about managing concurrency in C#.  The language is obviously different than the sql/python combination we covered in class, but otherwise the principles are the same.

Therefore, I will award extra credit for completing the game.  If you complete everything up to (and including) the "Locks" section, you will get +1 point ec.  Each additional section will award another +1 point up to +5 points maximum

**Comment by kushpetal** [comment]
Completed: 
- **Locks**
- **High-Level Synchronization Primitives**
- **Semaphores**

<img width="379" alt="Screen Shot 2023-05-16 at 11 04 19 AM" src="https://github.com/mikeizbicki/cmc-csci143/assets/63174413/23b0fbbc-0100-4b7f-b160-1703a17aaf5f">

**Comment by kevinm126** [comment]
Completed:
1. Locks
2. High-Level Synchronization Primitives
3. Semaphores
4. Condition Variables

<img width="411" alt="Screen Shot 2023-05-17 at 1 08 56 AM" src="https://github.com/mikeizbicki/cmc-csci143/assets/89937271/a7eeb1a6-8d2d-49ac-8562-8b9a81f45ac2">
