### ISSUE TITLE
Twitter coronavirus rerunning nohup

### ISSUE THREAD

**Issue by amytam01** [mikeizbicki/cmc-csci143#32]
Note: Shoutout to An for pointing out to me that my variable name is wrong (earlier issue, now reopened) :') 

Like mentioned in issue #31 I keep getting 
```
-bash: fork: retry: Resource temporarily unavailable
```

I fixed some pieces of my code after running nohup.
Currently my output folder only has `.lang` zip files. To fix this, I tried rerunning `nohup ./run_maps.sh` but it doesn't seem like `.country` zip files are being added to outputs. Any suggestions would be appreciated. Thanks! :)

**Comment by mikeizbicki** [comment]
My guess that not getting `.country` zip files is unrelated to #31, and is almost certainly due to an issue in your python code.  I would test your python code on only a single file, and once you're sure that it works there, run it on the large dataset with many processes.

**Comment by amytam01** [comment]
works now! I don't know what changed (maybe it was just waiting a few hours?)
