### ISSUE TITLE
Normalized insertion faster than expected

### ISSUE THREAD

**Issue by verynicocool** [mikeizbicki/cmc-csci143#320]
Before making any changes to the python code, I was running the load_tweets_sequential.sh file with bash in order to record the initial elapsed time before implementing in parallel. 

I recall in class that the normalized insertion was meant to take roughly ~10 minutes and that normalized_batch insertion should be significantly faster. However, I am getting that the normalized insertion takes 1m8.542s whereas the normalized_batch insertion takes around 2m51.554s. Denormalized took around 18s so it seems like denormalized and normalized_batch are inserting at the correct speed but normalized is inserting way faster than expected. 

Does anyone know why this might be happening? 

Here is the `load_tweets_sequential.sh` file:

```
  1 #!/bin/bash
  2
  3 files=$(find data/*)
  4
  5 echo '================================================================================'
  6 echo 'load denormalized'
  7 echo '================================================================================'
  8 time for file in $files; do
  9     unzip -p "$file" | sed 's/\\u0000//g' | psql postgresql://postgres:pass@localhost:4999/ -c "COPY tweets_jsonb (data) FROM STDIN csv quote e'\x01'     delimiter e'\x02';"
 10 done
 11
 12 echo '================================================================================'
 13 echo 'load pg_normalized'
 14 echo '================================================================================'
 15 time python3 -u load_tweets.py --db=postgresql://postgres:pass@localhost:5999/ --inputs $files
 16
 17 echo '================================================================================'
 18 echo 'load pg_normalized_batch'
 19 echo '================================================================================'
 20 time python3 -u load_tweets_batch.py --db=postgresql://postgres:pass@localhost:6999/ --inputs $files
```

**Comment by mikeizbicki** [comment]
The most likely cause is that the normalized insertion isn't actually inserting anything.

Recall that the unique constraints will prevent duplicate data from being inserted.  If the data has already been inserted, then the `insert` command will throw a unique constraint violation exception.  Detecting this violation will happen much faster than actually doing the insertion.  And so the code will run much faster if there is already data in the table.

To fix this problem, you have to delete the database and re-run the insertions.  You can do this by bringing down the containers and then deleting the volumes.

**Comment by verynicocool** [comment]
I thought that might be the issue as well but I tried bringing down the container and pruning the volumes several times and rerunning the `load_tweets_sequential.sh` but each time, I would get the exact same problem where Denormalized and Normalized_Batch run at accurate speeds but Normalized inserts way too fast. Do you have any other suggestions?

**Comment by mikeizbicki** [comment]
You can use
```
$ docker-compose pg_normalized_batch psql
> select count(*) from users;
```
to check whether the data has actually been deleted.  My guess is still that it hasn't.

There are many potential reasons why
```
$ docker volume prune
```
doesn't actually delete a volume.  You can verify that the volumes are deleted by running
```
$ docker volume ls
```
and you may need to manually delete them with
```
$ docker volume rm
```

**Comment by verynicocool** [comment]
Manually deleting the volumes fixed my problems!

Thanks Mike :)
