### ISSUE TITLE
No tables create in pg_normalized_batch

### ISSUE THREAD

**Issue by jp-microsoft** [mikeizbicki/cmc-csci143#321]
Hello,

I am running into an issue where all tables mentioned in `services/pg_normalized_batch/schema.sql` are not created when I build docker containers. When I checked what table are there using `docker-compose  exec pg_normalized_batch psql`, then `\d`, I don't see any table. This is what I get.

         List of relations
 Schema |       Name        | Type  |  Owner   
--------+-------------------+-------+----------
 public | geography_columns | view  | postgres
 public | geometry_columns  | view   | postgres
 public | spatial_ref_sys         | table  | postgres
(3 rows)

**Comment by tennisoctocat** [comment]
When you run `docker-compose logs`, do the logs look as expected for `pg_normalized_batch`? There might be errors in the schema.sql file that are preventing the tables from being created.

**Comment by jp-microsoft** [comment]
There is no errors/ anything suspicious in the logs. Also, I double-checked the schema.sql file. There is no issue.

**Comment by tennisoctocat** [comment]
I'm not sure then, sorry! When I spun up my containers, the tables would always be created so long as I saw the all of the CREATE TABLE commands and the COMMIT command in the log file.

**Comment by jp-microsoft** [comment]
It seems it is skipping the initialization because "PostgreSQL Database directory appears to contain a database". 

`pg_normalized_batch_1  | 
pg_normalized_batch_1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
pg_normalized_batch_1  | 
pg_normalized_batch_1  | 2023-04-12 06:49:37.046 UTC [1] LOG:  starting PostgreSQL 15.2 (Debian 15.2-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
pg_normalized_batch_1  | 2023-04-12 06:49:37.046 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
pg_normalized_batch_1  | 2023-04-12 06:49:37.046 UTC [1] LOG:  listening on IPv6 address "::", port 5432
pg_normalized_batch_1  | 2023-04-12 06:49:37.047 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
pg_normalized_batch_1  | 2023-04-12 06:49:37.053 UTC [29] LOG:  database system was shut down at 2023-04-12 06:49:33 UTC
pg_normalized_batch_1  | 2023-04-12 06:49:37.060 UTC [1] LOG:  database system is ready to accept connections
pg_normalized_batch_1  | 2023-04-12 06:54:37.108 UTC [27] LOG:  checkpoint starting: time
pg_normalized_batch_1  | 2023-04-12 06:54:37.114 UTC [27] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.002 s, sync=0.001 s, total=0.007 s; sync files=2, longest=0.001 s, average=0.001 s; distance=0 kB, estimate=0 kB`

**Comment by tennisoctocat** [comment]
Hm that might be because the volume still exists; what happens if you run the following?
```
docker-compose down
docker volume prune
docker-compose up -d --build
```

**Comment by jp-microsoft** [comment]
This one was not cleaning up the volumes well. That was the problem. 
`docker-compose down --volumes` solved my problem.
