### ISSUE TITLE
psql: could not connect to server: No such file or directory

### ISSUE THREAD

**Issue by Aser-Abdelfatah** [mikeizbicki/cmc-csci143#323]
When I run 
```
$ sh check_ansewrs.sh
```
 I get this error

```
psql: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
```
All the solutions on the internet include sudo commands, so I couldn't try them.

**Comment by tennisoctocat** [comment]
If you look at `docker-compose logs`, does it seem like `docker-compose up -d --build` finished? If so, you should see `listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"` somewhere in the logs.

I got this error when I had run  `docker-compose up -d --build` but the services weren't up and running yet, so waiting a bit worked for me.
