### ISSUE TITLE
Our baby has arrived :)

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/cmc-csci143#327]
My wife gave birth to Aurelia Love Izbicki two days ago on Sunday at 10:34.

Our son Evan picked the middle name.  He's been asking us to call the baby Love since he first learned he was going to have a baby sister.

My wife picked the first name.  She's always liked the name Aurelia.  (She reluctantly tolerates that I'll be using the name to teach our kids Latin.  In Latin, the name changes to "Aurelia", "Aureliae", or "Aureliam" depending on how its used in the sentence, and I'm teaching our other kids to use these different forms.  The actual name means "golden" and is the name of Caesar's mother.  Our son also wanted to name his baby sister "princess", and so we settled on a name for a famous "princess.")

Here's some pictures:

![baby0](https://user-images.githubusercontent.com/1052630/232868294-0c5ee421-0265-4a26-abba-2945ae6c5d57.jpeg)
![baby1](https://user-images.githubusercontent.com/1052630/232868309-a070bb36-6f65-4e35-b23c-b0bd49f96b7d.jpeg)

PS.  I'll post about my availability for final review when I know more details.

**Comment by verynicocool** [comment]
CONGRATULATIONS TO THE IZBICKIS !!!!!

**Comment by hfmandell** [comment]
Felicidades por tu chiquita! The Latin aspect of her name is spectacular.

**Comment by mhourani23** [comment]
awesome name

**Comment by ifreer23** [comment]
Congrats Mike!!

**Comment by sophiahuangg** [comment]
Congratulations!!

**Comment by samujala** [comment]
Congrats!!!

**Comment by samchotzen** [comment]
Congrats Mike!

**Comment by livrenfro** [comment]
Congratulations Mike!! Very meaningful name :)

**Comment by snarayan23** [comment]
Congrats!!

**Comment by mariagerges** [comment]
Huge Congrats Mike!! Very happy for you :)

**Comment by nishka-ayyar** [comment]
Congratulations Mike! Super fashionable baby

**Comment by KaranGoel1** [comment]
Congrats!!

**Comment by laurenleadbetter** [comment]
Beautiful! Congratulations Mike & fam :)

**Comment by kevinm126** [comment]
Congrats Mike!

**Comment by Aser-Abdelfatah** [comment]
Congrats!

**Comment by sybf-pro** [comment]
Congratulations, Mike, and the entire family on the arrival of your newborn! May God bless you all!
