### ISSUE TITLE
How to actually create Indexes.

### ISSUE THREAD

**Issue by BITEEE0308** [mikeizbicki/cmc-csci143#328]
Hi,

Does anyone know after I created the `schema-indexes.sql` file, how can the indexes be actually created? And how can we know they are actually being created?

I deleted all the data and volumes and containers and brought them back. It seems not working because the running time didn't change at all (about 2 mins). And when I went to the psql shell and checked all existing indexes, the new ones are not there. 

Thank you so much for help!

**Comment by mariagerges** [comment]
I have the same problem, I created the indexes but the runtimes are the same as before. were you able to figure it out?
