### ISSUE TITLE
404 Error trying to view my uploaded image

### ISSUE THREAD

**Issue by CurtisSalinger** [mikeizbicki/cmc-csci143#33]
Hello Mike and class,

I am running into issue in the final steps of my dockerizing project where I am able to get onto my website and get to the image upload page, however when I then try and go to view the image, I get a `404` error. I do not get an error output along the way so I am unsure where to go from here. My only irregularity is that when I run `docker-compose down -v`, I get the error shown below. Thanks for any guidance where to go from here!

<img width="952" alt="Screen Shot 2021-02-14 at 3 21 41 PM" src="https://user-images.githubusercontent.com/38367847/107888052-58fe8a80-6ed8-11eb-9bef-d8702fca9981.png">

**Comment by afzal-p** [comment]
Have you tried adding the image extension to the end of the url?

**Comment by CurtisSalinger** [comment]
I believe so, but I'll go back and confirm I did it correctly!

Update: Still no luck there, but thanks for the suggestion!

**Comment by mikeizbicki** [comment]
Sorry I missed this earlier.  I'm closing since I see you've already submitted the assignment, but if you still have questions about this I'd be happy to help.
