### ISSUE TITLE
Cannot log into Lambda Server.

### ISSUE THREAD

**Issue by BITEEE0308** [mikeizbicki/cmc-csci143#330]
Hi Mike,

I got stuck when I was still on the lambda server, and I was forced to quit. Then, when I'm trying to log in again now, it's giving me `client_loop: send disconnect: Broken pipe` error every time and I cannot log in. Is there any way to solve the problem?

@mikeizbicki 

Thanks for much for help!

**Comment by mariagerges** [comment]
+1

**Comment by samujala** [comment]
+1

**Comment by nishka-ayyar** [comment]
+1

**Comment by sophiahuangg** [comment]
+1

**Comment by snarayan23** [comment]
+1

**Comment by koffqq** [comment]
+1

**Comment by livrenfro** [comment]
+1

**Comment by laurenleadbetter** [comment]
+1

**Comment by KaranGoel1** [comment]
+1

**Comment by sybf-pro** [comment]
+1

**Comment by mikeizbicki** [comment]
Hmm... I'm also experiencing the connection outage.  I've contacted IT and asked them to restart the lambda server.  That'll probably happen sometime tomorrow morning when they come into the office.

Everyone can have an extension on the indexes homework until Thursday 20 April due to the outage.

**Comment by mikeizbicki** [comment]
The IT guys had a real fast turn around.  The server is back online now.
