### ISSUE TITLE
PostgreSQL Database directory appears to contain a database; Skipping initialization

### ISSUE THREAD

**Issue by BITEEE0308** [mikeizbicki/cmc-csci143#332]
Hi Mike!

I think I ran into the same problem in #174 for both normailized_batch and normalized. Deleting all data using the commands you offered did not solve the problem. 

It seems like you need to delete some directories to solve this? @mikeizbicki 

Thank you so much for help!

**Comment by BITEEE0308** [comment]
Hi Mike,

I tried to delete `$HOME/bigdata/pg_denormalized` and `$HOME/bigdata/pg_normalized_batch` you mentioned in #174 by myself, but it said `Permission denied`. I believe that means only you can delete it?

**Comment by ifreer23** [comment]
+1

**Comment by snarayan23** [comment]
+1

**Comment by mikeizbicki** [comment]
I've just run the following command
```
$ sudo rm -rf ../Sahana.Narayan.23/bigdata/* ../Ian.Freer.23/bigdata/* ../jzhao5793/bigdata*
```
which should hopefully fix all of your problems.  (Hopefully I translated everyone's github account name to the lambda server correctly.)

I'm guessing the commands listed in step 0.4 of the instructions would have deleted these files for you all, but in the interest of letting you all continue working without more back-and-forth I've gone ahead and deleted them.
