### ISSUE TITLE
No space left on device. Cannot clone the repo when I delete the original one and reclone.

### ISSUE THREAD

**Issue by BITEEE0308** [mikeizbicki/cmc-csci143#335]
Hi Mike,

When I  start bring the docker up again after you deleted the bigdata file, my `docker ps` command stopped working. Then, the terminal was indicating `-bash: cannot create temp file for here-document: No space left on device` all the time. 

When I tried to delete the whole repo and recloned it from my repo, it cannot be cloned now and it threw errors `fatal: write error: No space left on device | 22.37 MiB/s
fatal: fetch-pack: invalid index-pack output`. Do you know how to fix it? @mikeizbicki

**Comment by mikeizbicki** [comment]
This should be fixed now.  If I have time later today, I'll write a postmortem about what happened.
