### ISSUE TITLE
disk space issues: request to delete the databases

### ISSUE THREAD

**Issue by jp-microsoft** [mikeizbicki/cmc-csci143#355]
Hello,

I am running into issue, where loading data into the database stop with this message:

on load pg_denormalized:
`parallel: Error: Output is incomplete. Cannot append to buffer file in /tmp. Is the disk full?
parallel: Error: Change $TMPDIR with --tmpdir or use --compress.
Warning: unable to close filehandle properly: No space left on device during global destruction.
Command exited with non-zero status 255
0.48user 0.21system 22:52.11elapsed 0%CPU (0avgtext+0avgdata 18084maxresident)k
176inputs+32352outputs (1major+18853minor)pagefaults 0swaps` 

on load pg_normalized_batch:
`parallel: Error: Output is incomplete. Cannot append to buffer file in /tmp. Is the disk full?
parallel: Error: Change $TMPDIR with --tmpdir or use --compress.
Warning: unable to close filehandle properly: No space left on device during global destruction.
Command exited with non-zero status 255
0.26user 0.13system 0:01.24elapsed 31%CPU (0avgtext+0avgdata 17748maxresident)k
256inputs+1344outputs (2major+18106minor)pagefaults 0swaps
-bash: cannot create temp file for here-document: No space left on device`

When I check the logs, I see something like this: 
`pg_denormalized_1      | 2023-05-04 02:33:29.337 UTC [66] HINT:  Consider increasing the configuration parameter "max_wal_size".
pg_denormalized_1      | 2023-05-04 02:33:34.573 UTC [73] ERROR:  could not extend file "base/13445/16389": No space left on device
pg_denormalized_1      | 2023-05-04 02:33:34.573 UTC [73] HINT:  Check free disk space.
pg_denormalized_1      | 2023-05-04 02:33:34.573 UTC [73] CONTEXT:  COPY tweets_jsonb, line 1053139
pg_denormalized_1      | 2023-05-04 02:33:34.573 UTC [73] STATEMENT:  COPY tweets_jsonb (data) FROM STDIN csv quote e'\x01' delimiter e'\x02';
pg_denormalized_1      | Error grabbing logs: unexpected EOF`

**Comment by jp-microsoft** [comment]
Prof @mikeizbicki, could you delete my databases so that I start loading the data again?

**Comment by mhourani23** [comment]
+1 

`$ sh load_tweets_parallel.sh`

```
================================================================================
load pg_denormalized
================================================================================
Academic tradition requires you to cite works you base your article on.
When using programs that use GNU Parallel to process data for publication
please cite:

  O. Tange (2011): GNU Parallel - The Command-Line Power Tool,
  ;login: The USENIX Magazine, February 2011:42-47.

This helps funding further development; AND IT WON'T COST YOU A CENT.
If you pay 10000 EUR you should feel free to use GNU Parallel without citing.

To silence this citation notice: run 'parallel --citation'.

parallel: Error: Output is incomplete. Cannot append to buffer file in /tmp. Is the disk full?
parallel: Error: Change $TMPDIR with --tmpdir or use --compress.
Warning: unable to close filehandle properly: No space left on device during global destruction.
Command exited with non-zero status 255
0.45user 0.24system 17:33.53elapsed 0%CPU (0avgtext+0avgdata 18236maxresident)k
472inputs+25344outputs (6major+19276minor)pagefaults 0swaps
================================================================================
load pg_normalized_batch
================================================================================
Academic tradition requires you to cite works you base your article on.
When using programs that use GNU Parallel to process data for publication
please cite:

  O. Tange (2011): GNU Parallel - The Command-Line Power Tool,
  ;login: The USENIX Magazine, February 2011:42-47.

This helps funding further development; AND IT WON'T COST YOU A CENT.
If you pay 10000 EUR you should feel free to use GNU Parallel without citing.

To silence this citation notice: run 'parallel --citation'.

parallel: Error: Output is incomplete. Cannot append to buffer file in /tmp. Is the disk full?
parallel: Error: Change $TMPDIR with --tmpdir or use --compress.
Warning: unable to close filehandle properly: No space left on device during global destruction.
Command exited with non-zero status 255
0.29user 0.17system 0:00.56elapsed 83%CPU (0avgtext+0avgdata 18176maxresident)k
160inputs+0outputs (0major+19677minor)pagefaults 0swaps
-bash: cannot create temp file for here-document: No space left on device
```

**Comment by livrenfro** [comment]
\+ 1

**Comment by koffqq** [comment]
+1 
I am having problem deleting my ./../bigdata file. After deleting the bit mount, bring down docker, `rm -rf ./../bigdata` I am still getting the following error message. 
```
pg_denormalized_1      | 
pg_denormalized_1      | PostgreSQL Database directory appears to contain a database; Skipping initialization
pg_denormalized_1      | 
pg_denormalized_1      | postgres: could not access the server configuration file "/var/lib/postgresql/data/postgresql.conf": No such file or directory
pg_denormalized_1      | 
pg_denormalized_1      | PostgreSQL Database directory appears to contain a database; Skipping initialization
pg_denormalized_1      | 
pg_denormalized_1      | postgres: could not access the server configuration file "/var/lib/postgresql/data/postgresql.conf": No such file or directory
```

**Comment by sybf-pro** [comment]
+1
