### ISSUE TITLE
For non-graduating students: Your Grades in Sakai are Finalized

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/cmc-csci143#360]
All of the assignments have now been submitted and graded.  Your grade in sakai will be what I will be entering for you into the portal.  I'll enter grades Wednesday morning, so if there is a mistake in your grades you will have until then to let me know to correct it.

I hope you all have a great summer!

**Comment by KaranGoel1** [comment]
@mikeizbicki Would we be able to complete additional extra credit tasks by Wednesday morning, or is this only for corrections of completed work that may have been graded incorrectly? Thanks!

**Comment by sybf-pro** [comment]
+1

Also, Mike, I sent you an email. Let me know, please!

**Comment by mikeizbicki** [comment]
Yes, I'll still accept extra credit submissions.
