### ISSUE TITLE
Big Data student who took Data Structures 

### ISSUE THREAD

**Issue by irajmoradi** [mikeizbicki/cmc-csci143#367]
Hello,

When I try forking this repo it doesn't automatically work since I already have a fork of this repo from when I took data structures. Should I delete the old fork of this assignment and make a new one for big data and do the assignment, or just turn in the fork I have from data structures, or rename the old fork and create a new fork?

Sincerely,
Iraj James Moradi

**Comment by mikeizbicki** [comment]
I assuming you're referring to <https://github.com/mikeizbicki/continuous-integration/> and not this repo.

If you'd like more practice using github, you can delete your existing repo and redo the assignment.  If you feel comfortable with using github, however, than you are welcome to submit your existing repo as-is.
