### ISSUE TITLE
Lambda Server

### ISSUE THREAD

**Issue by oncelscu** [mikeizbicki/cmc-csci143#370]
Didn't get any emails from IT regarding the lambda server. Should I contact them?

**Comment by mikeizbicki** [comment]
Everyone should have received an email from either <help@cmc.edu> or <Jeffrey.Ng@ClaremontMcKenna.edu> account details for the VPN.  If you didn't get that email, you should contact CMC's IT help desk.

Separately, you should have received an email from me with lambda server credentials.  If you didn't get that, then let me know tomorrow before class and I'll create one for you.

**Comment by myngpog** [comment]
Do you know if cmc it has an email I can reach? Thanks! @mikeizbicki

**Comment by mikeizbicki** [comment]
@myngpog I'm not sure what you're asking for.  I provided the email help@cmc.edu in the message you replied to.
