### ISSUE TITLE
Git Pull Tutorial

### ISSUE THREAD

**Issue by mmendiratta27** [mikeizbicki/cmc-csci143#371]
Hi!

I have been working through the Git Pull Tutorial but faced an issue when trying to push my updated file. I followed all steps until the push command exactly as written on the tutorial and have included an image of the issue for reference. Any suggestions?

<img width="586" alt="Screenshot 2024-01-17 at 4 44 05 PM" src="https://github.com/mikeizbicki/cmc-csci143/assets/123344066/d6fa5b2e-ea15-4a1f-bc7e-918619329ede">

**Comment by mikeizbicki** [comment]
In the `hint` section of your screenshot it gives a solution that will probably fix your problem.  Is says:
```
hint: use 'git pull' before pushing again.`
```

We'll cover using git more starting next week, so it's okay if you can't get things working until then.

----

Also, you shouldn't post screenshots of text to github.  Instead, copy-paste the text into the issue using a code block.  Images are much less usable for many reasons:

1. I cannot copy/paste from your output.

1. You're font/coloring scheme can be hard to read for some people.  By copy/pasting, you allow people to use their own font/coloring schemes.

1. Blind people (or anyone using a screen reader) will not be able to read your text.

1. Google will not be able to read the content of the image.  Therefore, your question (and the resulting answer) will never appear in search results.

1. The full context often doesn't fit on a single screen.

If you report problems  on github using images, this looks unprofessional and people will be less inclined to help you out.
