### ISSUE TITLE
Issue Installing VPN

### ISSUE THREAD

**Issue by henrylong612** [mikeizbicki/cmc-csci143#373]
Hi @mikeizbicki,

When I tried to download the VPN through the school, it made me download Duo, which required my Mac to have the latest software installed. Since I did not have the storage to do so, I have been in the ITS office since 8am sharp moving my storage every which way so that maybe, just maybe I can update my computer and install the VPN. It's looking like I might still have more than a few hours to go, meaning that I will probably miss the lab today. I noticed that the lab has some in-class components that I would miss. Is there any way I could make these up?

Thank you for your understanding...

**Comment by mikeizbicki** [comment]
Hmm... in general you can always make up these "in person required" portions of labs in the QCL or by coming to a different lab section.  This particular lab's component is short enough that you could also do it before a lecture period sometime next week.

Another fix to your underlying problem might be the `openconnect-sso` package.  Google Bard tells me this (or a couple of other similar techniques) should work, and although I haven't tested it out, it makes sense to me that it would.  I'd be happy to try to work through the `No SSL Handler` errors with you or anyone else in lab today.
