### ISSUE TITLE
lab part 1 issue

### ISSUE THREAD

**Issue by JTan242** [mikeizbicki/cmc-csci143#379]
I've been having trouble with the last part of lab part 1. I've tried reloading things but I ended up messing up some of my data because when I input:  sqlite> select count(*) from interactions; 
I get 39999 where I should be getting just 9999.

How can I reset this back to normal?

**Comment by ains-arch** [comment]
There might be a better way but I think you should be able to delete the `goodreads.db` file with `rm goodreads.db` in the shell and then restart from the beginning of part 3.
