### ISSUE TITLE
Unable to access the pagila-hw repo from the week3 link

### ISSUE THREAD

**Issue by saatvik7** [mikeizbicki/cmc-csci143#38]
Hi! So, when I try to access the pagila-hw from the week3 directory it is giving me a 404 error at this [link](https://github.com/mikeizbicki/pagila-hw/tree/e984c5840046a4dd2d9b388bffc2227e963cba46). However, the repo at https://github.com/mikeizbicki/pagila-hw works and I was wondering if this is the same as the one in the week3 folder. Thank you!

**Comment by mikeizbicki** [comment]
I've fixed the broken link within the `week_03` directory.  (Thanks for pointing that out, and sorry about that mistake.)  

Yes, the link you provided goes to the same spot.
