### ISSUE TITLE
Continuous-Integration CI badge Question

### ISSUE THREAD

**Issue by sjanefullerton** [mikeizbicki/cmc-csci143#384]
Hi @mikeizbicki,

For the continuous-integration homework, I am having trouble getting the badge to display green. Should I be changing the username for both links in the top line? If I change just the first link to my username, the badge remains red even though I am passing all test cases. However, if I change both links, the README displays as the following without any badge:
Continuous Integration https://github.com/sjanefullerton/continuous-integration/actions?query=workflow%3Atests

Is there a step I might be missing when updating the README.md file? Thank you for your help!

[https://github.com/sjanefullerton/continuous-integration](url)

**Comment by epaisano** [comment]
Hey @sjanefullerton! I see your link doesn't point to your repo (ie: I don't see your username in the second line, which may be causing the issue). For example, this is the entire first line of my README file:
```# Continuous Integration ![https://github.com/epaisano/continuous-integration/actions?query=workflow%3Atests](https://github.com/epaisano/continuous-integration/workflows/tests/badge.svg)```
Hope this helps!

**Comment by sjanefullerton** [comment]
That worked! Thank you so much!!
