### ISSUE TITLE
Continuous Integration CI Badge Issues

### ISSUE THREAD

**Issue by ValentinaWatson** [mikeizbicki/cmc-csci143#387]
When I just change the username for the badge link, it displays on the README as a hyperlink instead of the photo of the badge. I currently have it written as below:

```
# Continuous Integration ![https://github.com/ValentinaWatson/continuous-integration/actions?query=workflow%3Atests](https://github.com/ValentinaWatson/continuous-integration/workflows/tests/badge.svg)
```

**Comment by mikeizbicki** [comment]
If you visit the "actions" tab of your repo: <https://github.com/ValentinaWatson/continuous-integration/actions>, you'll see that you don't have any github actions (i.e. the test cases) that have been run.

First, you'll need to enable github actions.  You should see a button somewhere on the link above to do so.

One actions is enabled, the actions will run for every new commit that you make.  So you'll need to make a new commit (a trivial commit changing something like whitespace is fine), and push it to github.  You should see actions running in the actions tab linked above once you've done that.  Once the actions complete, the badge will turn red/green depending on if it was successful.
