### ISSUE TITLE
Zoom/Youtube playlist

### ISSUE THREAD

**Issue by abraryaser02** [mikeizbicki/cmc-csci143#388]
Good morning Professor! I tried zooming into class today but the link seems to not be working. Is it possible to upload today's lecture on YouTube too? Also, last Thursday's lecture video is unavailable on YT on my end. How should I access it? Thank you.

**Comment by mikeizbicki** [comment]
The zoom link was broken, sorry.  It should be fixed now.  All three class videos should now be uploaded.
