### ISSUE TITLE
Question about Part 5 of lab-posix-mapreduce

### ISSUE THREAD

**Issue by henrylong612** [mikeizbicki/cmc-csci143#391]
Hi @mikeizbicki,

When I run the code provided in Part 5 of lab-posix-mapreduce, I get a messy plot with every single country of origin on the x-axis. Should I leave this as-is, or limit my graph to the top 10/20 countries of origin?

**Comment by mikeizbicki** [comment]
Either way is fine.  I originally intended to have the instructions tell you to limit it to the top 10 countries like in Part 4.  But since I forgot to add that instruction, I'll accept either graph as full credit.
