### ISSUE TITLE
Part 5 lab-posix-mapreduce

### ISSUE THREAD

**Issue by ValentinaWatson** [mikeizbicki/cmc-csci143#392]
I'm doing the exercise for part 5 of the lab and I'm not able to successfully produce an image. My colors.png and top10.png are showing up so I don't think my boxplot.gp is wrong. I'm currently running the mapper and reducer then the line:

` cat 'reduce' | gnuplot -c boxplot.gp country_code_mapreduce.png `

I feel like this line is the most likely reason for my lack of success but let me know if I'm missing something. I've also added the link to my repository if that would be helpful.

https://github.com/ValentinaWatson/lab-posix-mapreduce

**Comment by irajmoradi** [comment]
I would recommend trying 
```cat 'reduce'```

If you get a blank output that likely means you did the reduce step before the map step was done. The map step takes like 5 minutes to do from the time you enter the command, it just works in the background.
