### ISSUE TITLE
lab section 6 disk quota 

### ISSUE THREAD

**Issue by giffiecode** [mikeizbicki/cmc-csci143#395]
for file in /data/Twitter\ dataset/geoTwitter20-01-0*.zip; do 
    unzip -p "$file" \
    | jq -c '. | select(.place.country_code == "US") | .lang' \
    | sort \
    | uniq -c \
    | sort -n \
    > map_uslang.$(basename "$file").dat &
done 

= 

the above is the script I ran to get the lang data for tweets sent from US. I run into sort: write failed: /tmp/sorth9JPq1: Disk quota exceeded
sort: write failed: /tmp/sortaT3CSn: Disk quota exceeded
sort: write failed: /tmp/sortUiUVeE: Disk quota exceeded
sort: write failed: /tmp/sortYoTuKF: Disk quota exceeded
sort: write failed: /tmp/sortl6lwjl: Disk quota exceeded
sort: write failed: /tmp/sortZgvrYt: Disk quota exceeded
sort: write failed: /tmp/sortFpNi2k: Disk quota exceeded

and all the map_uslang files were created but empty

**Comment by mikeizbicki** [comment]
I'm closing this issue for two reasons. First, your code is not formatted using markdown with code blocks, so it's hard to read.  In general, it is polite on the internet to always format everything with markdown.  Second, I don't see any question in your post, so it's not clear to me what type of response you're looking for.

If you fix these issues and repost, I'd be happy to respond.
