### ISSUE TITLE
Part 5 of lab-posix-mapreduce issue

### ISSUE THREAD

**Issue by sjanefullerton** [mikeizbicki/cmc-csci143#396]
Hi,

I have been trying to generate the country_code_mapreduce.png for part 5 of the lab. However, after running the map and reducer, I get an error when I try to create the png.

I enter the following in the terminal:
`
$ cat 'reduce' | gnuplot -c boxplot.gp country_code_mapreduce.png
`

I get the following output:

"boxplot.gp", line 5: warning: Skipping data file with no valid points
plot '/dev/stdin' using 1:xtic(2) notitle
                                                              ^
"boxplot.gp", line 5: x range is invalid

I still have a file country_code_mapreduce.png that gets created, but it does not contain anything.

**Comment by ains-arch** [comment]
Have you tried [this](https://github.com/mikeizbicki/cmc-csci143/issues/392#issuecomment-1913359275)?

**Comment by mikeizbicki** [comment]
I'm closing this issue because the original question isn't using markdown properly, which makes it hard for me to read and understand.  If you're still having problems, feel free to repost with correct markdown formatting and I'd be happy to help.
