### ISSUE TITLE
Audio issue with class recording

### ISSUE THREAD

**Issue by baron-zeng** [mikeizbicki/cmc-csci143#401]
Hi Mike,

The audio for the class recording from today (1/30 Posix 2+3) does not seem to work. Do you mind re-uploading it?

Thank you,
Baron

**Comment by mikeizbicki** [comment]
Hmm... it looks like I forgot to unmute my mic prior to recording.  So there's no way to recover the audio, sorry.

If you'd like to watch a lecture-style review of the posix 2/3 material, I recommend the lectures from CS46 on the same material.  They're also a little bit slower paced, which some students may find more helpful anyways.  I've tried to provide links below that go directly to the discussions of the material and skip over unrelated/administrative stuff.

1. CS46 POSIX 2 Lecture (part 1): <https://www.youtube.com/watch?v=4BkIoN_8-cE&t=2420s>
2. CS46 POSIX 2 Lecture (part 2): <https://www.youtube.com/watch?v=zjCJU5CrvZs&t=3m40s>
3. CS46 POSIX 3 Lecture: <https://www.youtube.com/watch?v=m0qJWHu7rNU&t=608s>
