### ISSUE TITLE
Docker Installation Issues

### ISSUE THREAD

**Issue by baron-zeng** [mikeizbicki/cmc-csci143#405]
Hi Mike,

My docker installation seems successful after I run:

```
$ curl -fsSL https://get.docker.com/rootless | sh
``` 

However, I get the following error after testing:

```
$ docker
```

<img width="513" alt="Screenshot 2024-02-01 at 14 27 39" src="https://github.com/mikeizbicki/cmc-csci143/assets/123041586/83e27305-6a5c-4fd7-8eed-0900a1044de3">

To get docker to work, do I just need to run:

```
$ apt install docker.io
```

Thank you,
Baron

**Comment by mikeizbicki** [comment]
I'm closing because screenshots are never an acceptable method of posting text online.  If you repost with correct formatting, I'll answer.

**Comment by baron-zeng** [comment]
Sorry about the screenshot. The docker seems to work fine now after I quit and re-entered terminal.

Thank you,
Baron
