### ISSUE TITLE
Type of CHAR in Lab05

### ISSUE THREAD

**Issue by anan-ara** [mikeizbicki/cmc-csci143#41]
I believe that the type CHAR in sql has typalign: c and typlen: 1, but when using the query from https://www.2ndquadrant.com/en/blog/on-rocks-and-sand/ I get that "b CHAR" from the "example" table actually is type "bpchar" has typalign: i  and typlen: -1.

So is "b CHAR" from the "example" table a "char" type or a "bpchar" type?

**Comment by mikeizbicki** [comment]
`char` in postgres does not represent an individual character, but rather a string similar to `text`.  That is why it has the `typlen` equal to 1.  In general, the queries presented in that link show the ground truth of how things are represented in postgres, and so if any other source says something different, the other source must be wrong.

PS.  In the future, you should be using backticks for your sql code to make it more readable.
