### ISSUE TITLE
Lambda Server Connection Issue

### ISSUE THREAD

**Issue by gibsonfriedman** [mikeizbicki/cmc-csci143#410]
Hi @mikeizbicki,

Whenever I try to log onto the lambda server I am using the command you provided us and I'm getting this error message. I'm connected to the vpn and using the correct username but I'm unsure why this error is coming up. 

ssh: Could not resolve hostname lambda.compute.cmc.edu: nodename nor servname provided, or not known

**Comment by abizermamnoon** [comment]
Have you connected to the vpn?

**Comment by gibsonfriedman** [comment]
@abizermamnoon Yeah I connected and then tried restarting it but that didn’t make the error stop.

**Comment by abizermamnoon** [comment]
can you share the ssh command you use to connect to the lambda server?

**Comment by gibsonfriedman** [comment]
@abizermamnoon ssh gfriedman25@lambda.compute.cmc.edu -p 5055

**Comment by henrylong612** [comment]
@mikeizbicki @gibsonfriedman @abizermamnoon I am running into the same issue

**Comment by mikeizbicki** [comment]
I've just checked and the lambda server is up.  The error message 
```
Could not resolve hostname lambda.compute.cmc.edu: nodename nor servname provided, or not known
```
Indicates that you were not connected to the vpn for some reason.

PS.  In the future, everything that is copy/pasted from the terminal (which includes both error messages and commands) should be in code blocks.
