### ISSUE TITLE
can't open the app on firefox browser 

### ISSUE THREAD

**Issue by giffiecode** [mikeizbicki/cmc-csci143#416]
i changed the port in the app.py file to 9999, used localhost:6666:localhost:9999 to run and access. I can open the the app through links http://localhost:9999 but can't open it through firefox via localhost:6666

<img width="1792" alt="Screen Shot 2024-02-06 at 11 14 20 AM" src="https://github.com/mikeizbicki/cmc-csci143/assets/123010051/f75127d7-4ff6-4efb-a528-43b0d8c3ba67">

**Comment by giffiecode** [comment]
my question is how to open this on firefox?

**Comment by mikeizbicki** [comment]
If links works and firefox does not, that means that the problem is in the ssh port forwarding.  You'll need to fix your `-L` flag in the `ssh` command.  Sorry I can't tell you exactly what to put there, but the right incantation there should fix everything.

**Comment by giffiecode** [comment]
channel 3: open failed: connect failed: Connection refused 

i got this error in the terminal when I try to open the website through browser. Seems like the browser is connected to the terminal but couldn't open the website. How to proceed from here?
