### ISSUE TITLE
can't upload the screenshot

### ISSUE THREAD

**Issue by nati-azmera** [mikeizbicki/cmc-csci143#419]
Hello,

I've been trying to upload the screenshot of the FireFox tab onto my repo but I keep on getting this error message, "Something went really wrong, and we can’t process that file." I've tried exporting it into a different file type (JPEG, PNG...) and have also tried using a different browser, but it still isn't working. Does anyone have any suggestions?

**Comment by abizermamnoon** [comment]
Hi, 

I used the [scp command](https://www.geeksforgeeks.org/scp-command-in-linux-with-examples/) to transfer files from my local computer to the directory in the lambda server

**Comment by mikeizbicki** [comment]
@nati-azmera My guess is that you are trying to use the github interface to upload the file.  Instead, you should use the git terminal commands to upload the file.  You can do this directly from your laptop without transferring the file to the lambda server first.
