### ISSUE TITLE
Flask_web HW Rick Roll Page

### ISSUE THREAD

**Issue by baron-zeng** [mikeizbicki/cmc-csci143#420]
Hey guys,

For the hw, I just wanted to confirm that when we go to a browser and open the localhost URL, we should NOT get a rick rolled page, correct?

This is my SSH command:

```
ssh Baron.Zeng.24@lambda.compute.cmc.edu -p 5055 -L localhost:3002:10.253.1.15:1333
```

This is my docker run command, which works fine:

```
docker run -it  hashcode
```

Does anyone know what the issue might be?

Thank you,
Baron

**Comment by baron-zeng** [comment]
Sorry, I thought I solved the problem but didn’t.

**Comment by justinchiao** [comment]
Not sure if this would fix it, but I used this:
```
ssh jchiao@lambda.compute.cmc.edu -p 5055 -L localhost:8080:0.0.0.0:1333
```
I think the name should be match that of the container and not the lambda server.
