### ISSUE TITLE
README Creation

### ISSUE THREAD

**Issue by henrylong612** [mikeizbicki/cmc-csci143#428]
Hi @mikeizbicki,

testdrivenio has a README describing their project [here](https://github.com/testdrivenio/flask-on-docker). Are we able to borrow parts of this README to include in our README for this project?

**Comment by mikeizbicki** [comment]
Yes, that's fine.  You can reuse their wording, just provide a link back to their project if you do.

**Comment by henrylong612** [comment]
Thank you!
