### ISSUE TITLE
GitHub Actions down

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/cmc-csci143#43]
GitHub actions is currently experiencing an outage, and so homeworks submitted will not be able to run the CI checks.

To submit your assignments, please wait until GitHub Actions is back online so that you can get the test cases to run.  These sort of outages are usually short (few hours max), but no one will experience a late penalty who is affected by this.

See https://www.githubstatus.com/ for details about the issues.

**Comment by amytam01** [comment]
Some of us also aren't able to access the server! (but this is probably a separate issue)

**Comment by mikeizbicki** [comment]
Github's downtime seems to be caused by a larger problem with Microsoft Azure (see https://status.azure.com/en-us/status).  Microsoft purchased github a while back, and so presumably github is operating with Azure infrastructure.

This shouldn't cause an issue with the lambda server.  I can still connect to it fine, for example.

**Comment by amytam01** [comment]
The server works now! :)
