### ISSUE TITLE
can't access server port in docker section

### ISSUE THREAD

**Issue by giffiecode** [mikeizbicki/cmc-csci143#431]
``` 
Yuechen.Pei.23@lambda-server:~/flask-on-docker$ docker ps
CONTAINER ID   IMAGE                 COMMAND                  CREATED          STATUS         PORTS                                         NAMES
5ce9fe2438d8   flask-on-docker_web   "python manage.py ru…"   26 minutes ago   Up 3 seconds   0.0.0.0:22222->5000/tcp, :::22222->5000/tcp   flask-on-docker_web_1
``` 

I got the the return above, indicating that my docker task is running correctly. I then run 
`
curl http://localhost:22222
`
but got  
```
curl: (52) Empty reply from server
```
instead of the json containing hello world. anyone knows how to resolve this issue?

**Comment by mikeizbicki** [comment]
You're correct that the port 5000 on the container has been routed to 22222 on the lambda server.  Port 5000 is the default port for flask, but likely you have changed this somewhere to be something else.  You should look for all the instances of 5000 in the tutorial and ensure that you still have it set to 5000 in your code.

**Comment by giffiecode** [comment]
resolved! it was in my .env.dev file that the port was set to 22222 instead of 5000. thank @mikeizbicki
