### ISSUE TITLE
Error in Postgres.: issue running container

### ISSUE THREAD

**Issue by meghnapamula** [mikeizbicki/cmc-csci143#432]
Hello, 

I am in the last step of the Postgres section of the homework and I have a question regarding my port number.

```
$ docker build -f ./services/web/Dockerfile -t hello_flask:latest ./services/web

$ docker run -p 6001:5000 \
    -e "FLASK_APP=project/__init__.py" -e "FLASK_DEBUG=1" \
    hello_flask python /usr/src/app/manage.py run -h 0.0.0.0 `
```

I am able to run the first command (the build command) just fine.  However, when I try to run the second command, I encounter the following error:

```
docker: Error response from daemon: driver failed programming external connectivity on endpoint zealous_chebyshev (cc939e61fb99473d5103203e9d2e4e6a4de3063e7d0846ae9e9b4f07216cacbf): Bind for 0.0.0.0:6001 failed: port is already allocated.
ERRO[0000] error waiting for container: context canceled
```

I have been using port 6001, and I see that this error says that that port is already allocated.  Does this mean that I should switch to another port number?  And if so, should I make this switch in every single location where I have used port 6001?

**Comment by mikeizbicki** [comment]
You've diagnosed the problem 100% correctly, good job :)

I'll just add that in the step of the tutorial you're running, you already have a flask server running on port 6001.  (This is the flask server defined in the `docker-compose.yml` file.)  This is why there is already something running on that port.  The point of this step is to illustrate that you can run two independent web servers at the same time.  And they both can't use the same port, so you have to change the port number of the second one.
