### ISSUE TITLE
Twitter-Coronavirus Task4 Hashtags Query

### ISSUE THREAD

**Issue by AvidThinkerArsum** [mikeizbicki/cmc-csci143#437]
Hey all,

Some questions regarding Task4:

Should our file work for any hashtags or are we dealing only with the hashtags listed on the map.py file?
It does not ask for plots specifically, so are we supposed to present plots for a hashtag of choice?

**Comment by mikeizbicki** [comment]
Good questions.

> Should our file work for any hashtags or are we dealing only with the hashtags listed on the map.py file?

My solution `alternative_reduce.py` file takes a list of hashtags as command line parameters.  I find that writing more general code in this way is ultimately easier, but you're free to do whatever you'd like.

> It does not ask for plots specifically, so are we supposed to present plots for a hashtag of choice?

Plot at least the two largest on a single graph.  You're welcome to plot more as well.

**Comment by lbielicki** [comment]
@mikeizbicki could you clarify what you mean by the "two largest"? and is the idea that task4 should look the same for everyone as well, instead of choosing our own hashtags? (edit: I ask because made my plots assuming that we should choose our own)

**Comment by mikeizbicki** [comment]
I just want you to select "reasonable looking" hashtags.  For example, `#nurse` has very few tweets, and so there's nothing interesting to look at.  `#covid19` has lots of tweets, and so there is something interesting to look at.  If you're unsure if you're including the right hashtags, it's not wrong to include more.  In particular, it's not wrong to include every hash tag; you're just not required to.

PS. I realize that the ambiguous-ness of the requirement is awkward from a student perspective where you care about what your grade will be.  In the real world, however, most problem specifications are ambiguous and boil down to "be reasonable".  So these instructions are intended to get you practice with ambiguity.
