### ISSUE TITLE
nginx question 

### ISSUE THREAD

**Issue by danzhechen** [mikeizbicki/cmc-csci143#438]
Hi friends,  

I was working on the section of Nginx. I have a question regarding the ports that we need to add to _docker-compose.prod.yml_:
```
nginx:
  build: ./services/nginx
  ports:
    - 1337:80
  depends_on:
    - web
```

Among this part, the tuition asked us to set up nginx on ports 1337. I tried to set up my yml file in this way. And after everything, when I connect to http://localhost:1337/, it does not show anything but only 
```
channel 3: open failed: connect failed: Connection refused
channel 3: open failed: connect failed: Connection refused
channel 3: open failed: connect failed: Connection refused
channel 3: open failed: connect failed: Connection refused
channel 3: open failed: connect failed: Connection refused
```
I checked the log for my docker, it seems everything works. I also shifted the ssh login information for my lambda server to localhost:1337. It still shows the error message. 

So I changed the above ports to 5050 for a test. Since the lambda server only uses port 5050, and it seems it works. 

I wonder whether this is supposed to happened and if so why is this the case?

**Comment by mikeizbicki** [comment]
Recall that in the port specification `1337:80`, the number to the right of the colon is the port on the container, and the number to the left of the colon is the port on the computer that you are running docker (which is the lambda server).  They way you wrote your issue, it sounds like you were connecting to `localhost:1337` on your laptop.  This could only work if you have port forwarding setup (and you should set that up to make it work).
