### ISSUE TITLE
How to uncommit single file from git

### ISSUE THREAD

**Issue by baron-zeng** [mikeizbicki/cmc-csci143#439]
Hello @mikeizbicki ,

For the flask-on-docker hw, I have been using different branches and committing each branch before merging it back to master. I did these commits before creating my ```.gitignore``` file. How can I de-commit a single file (```.env.prod.db``` )?

The solutions online mainly address situations where you want to undo a previous commit, but I created the ```.env.prod.db```  a few commits ago and do not want to risk messing up all my progress.

If I created a ```.gitignore``` file now and added ```.env.prod.db``` to it, would it still be pushed onto github (```.env.prod.db``` has already been committed)?

Thank you,
Baron

**Comment by mikeizbicki** [comment]
Fantastic question.

The right way to think of git commits is as immutable objects that can never be changed.  It is therefore possible to create a new commit that deletes this file, but the file still exists in the previous commits and therefore could be viewed by an attacker.  

The simplest way to recover from this situation is to delete the git history and start again.  This would involve running `rm -rf .git` on the `.git` folder only, and not on the entirety of your project folder.  Then rerunning the `git init` command.
