### ISSUE TITLE
midterm SQL folder issue

### ISSUE THREAD

**Issue by amytam01** [mikeizbicki/cmc-csci143#44]
I couldn't clone the SQL folder for some odd reason (everything else I could pull from Github) so I ended up just copying over all the sql files--will this cause any errors, particularly for 05.sql? Alternatively, should I continue trying to clone the SQL folder? Thank you! :)

**Comment by samuellee19** [comment]
Switching branch worked fine with me

**Comment by mikeizbicki** [comment]
The `sql` folder is contained with the `master` branch.  The default branch was previously the `no_sql` branch, which did not contain the problems.  I've changed the default branch now to master, so any subsequent calls to `git clone` will get the `master` branch.  If you've already cloned the repo, then a simple `git checkout master` should get you the `sql` folder; alternatively, you can re-clone the repo and it should just work.
