### ISSUE TITLE
Production Dockerfile Issue

### ISSUE THREAD

**Issue by Yugi00** [mikeizbicki/cmc-csci143#442]
Currently trying to build a docker image with the new `Dockerfile.prod` file in the tutorial, however I have received this error:
```
Step 19/27 : COPY --from=builder /usr/src/app/wheels /wheels
invalid from flag value builder: pull access denied for builder, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
ERROR: Service 'web' failed to build : Build failed
```
I believe my `Dockerfile.prod` is correct, but this is the portion the error is referring to:
```
# install dependencies
 49 RUN apt-get update && apt-get install -y --no-install-recommends netcat
 50 COPY --from=builder /usr/src/app/wheels /wheels
 51 COPY --from=builder /usr/src/app/requirements.txt .
 52 RUN pip install --upgrade pip
 53 RUN pip install --no-cache /wheels/*
```
Any help resolving this issue would be great!

**Comment by mikeizbicki** [comment]
This is a great question, and excellently asked.  I've copy/pasted the question into google bard, and I believe the answer will resolve your problem.  You can find it at <https://gemini.google.com/share/39b71491debf?hl=en>.
