### ISSUE TITLE
sql.11 

### ISSUE THREAD

**Issue by giffiecode** [mikeizbicki/cmc-csci143#446]
I noticed that the result is sorted in descending order in terms of film_id, except 

```
417 | HILLS NEIGHBORS      |     6
     415 | HIGH ENCINO          |     6
     416 | HIGHBALL POTTER      |     6
     414 | HELLFIGHTERS SIERRA  |     6
     
 ``` 
 
 the above is from `expected/11.out`
 
 I wonder if this is an error in the expected file?

**Comment by giffiecode** [comment]
```
 GROSSE WONDERFUL            |     384 |           4
 GUNFIGHTER MUSSOLINI        |     389 |           4
 GUNFIGHT MOON               |     388 |           4
``` 

same problem for the previous issue i posted

**Comment by mikeizbicki** [comment]
There are no errors in the `expected` folder.  The folder was just copied from the `results` folder of my solution, so there definitely exists a sql command that will generate the expected output.

There may be some poorly worded questions.  I would be happy to accept pull requests that fix/clarify question wording, and would assign appropriate extra credit for doing so.

**Comment by echen4628** [comment]
I think the results are actually sorted in reverse alphabetical order in terms of the `title`. 
```
417 | HILLS NEIGHBORS      |     6
415 | HIGH ENCINO          |     6
416 | HIGHBALL POTTER      |     6
414 | HELLFIGHTERS SIERRA  |     6
```
"L" comes after "G," so "HILLS NEIGHBORS" before "HIGH ENCINO."
