### ISSUE TITLE
pagila hw tests show no status

### ISSUE THREAD

**Issue by JTan242** [mikeizbicki/cmc-csci143#455]
I got all my tests to pass but when I pushed my files into GitHub it shows "Test No Status". Also when I go into actions it just says "this workflow has no runs yet." I believe I changed the badge in the README properly and changed the yaml file to run the right script, so if someone knows if I need to change anything else please let me know.

**Comment by mikeizbicki** [comment]
Github actions only run when you push a commit.  Most likely you enabled github actions after pushing, and so nothing is being run.  If you make another commit and push that commit, then the actions should run.

**Comment by JTan242** [comment]
Yeah that worked thanks!

**Comment by JTan242** [comment]
yeah that worked thanks!
