### ISSUE TITLE
Disk Quota Exceeded When Cloning in Lambda

### ISSUE THREAD

**Issue by mmendiratta27** [mikeizbicki/cmc-csci143#459]
When I try to clone the pagila-hw2 repository, I get a `Disk quota exceeded` error on the lambda server.

```
$ git clone https://gitlab.com/mikeizbicki/pagila-hw2
fatal: could not create work tree dir 'pagila-hw2': Disk quota exceeded
```

This also happens when I try using tab complete.
```
-bash: cannot create temp file for here-document: Disk quota exceeded
```

Any suggestions on how to fix this? Thanks!

**Comment by mikeizbicki** [comment]
You have 10GB of space allocated in your home folder.  You'll need to find the files that are taking up all this space and delete them.  You can use the command
```
$ du -hd1
```
in your home folder to list how much space each of the directories is taking up.  Find the directories > 1GB and see if there's anything in there you can delete.

**Comment by mmendiratta27** [comment]
Cleared up some space, thank you!
