### ISSUE TITLE
Pagila-hw2 Docker Compose Issue

### ISSUE THREAD

**Issue by gibsonfriedman** [mikeizbicki/cmc-csci143#460]
Whenever I try to run `docker-compose up -d --build` on the second pagila hw I get this error 

`Step 6/7 : COPY ./pagila/pagila-schema.sql /docker-entrypoint-initdb.d/01.sql
COPY failed: file not found in build context or excluded by .dockerignore: stat pagila/pagila-schema.sql: file does not exist
ERROR: Service 'pg' failed to build : Build failed
`

If anyone else has had the same error or knows of a fix I'd really appreciate it!

**Comment by henrylong612** [comment]
Did you init the submodules?

**Comment by gibsonfriedman** [comment]
I did a while ago but doing it again seemed to fix it.
