### ISSUE TITLE
pagila-hw3 problem 15 rating mix up

### ISSUE THREAD

**Issue by tylerheadley** [mikeizbicki/cmc-csci143#463]
Just a heads up in case anyone gets stuck on this like I did, problem 15 on pagila-hw3 the problem says to find documentaries rated PG, however the expected actually seems to contains documentaries rated G.

**Comment by henrylong612** [comment]
This was helpful, thank you @tylerheadley!

**Comment by mikeizbicki** [comment]
Thank you!

I've updated the problem statement to reflect this change.  (There is no need for anyone to reclone/pull the contents from github, but you're welcome to if you'd like to.)
