### ISSUE TITLE
pagila-hw3 setup errors

### ISSUE THREAD

**Issue by epaisano** [mikeizbicki/cmc-csci143#464]
Hello! I am trying to get the data to update for the pagila hw using the instructions from the pagila-hw3 repo. However, once I change to the master branch and bring down my containers and then build them again, I am getting the following errors:

```
Recreating pgadmin4_container ... 
Recreating pgadmin4_container ... error
WARNING: Host is already in use by another container

ERROR: for pgadmin4_container  Cannot start service pgadmin: driver failed programming external connectivity on endpoint pgadmin4_container (f048adfe023e7821b17cd1f8b9c47ca8135c644db3461973712a0f6d192f4a61): Error starting userland proxy: error while calling PortManager.AddPort(): listen tcp4 0.0.0.0:5050: bind: address already in use
Recreating pagila             ... error

ERROR: for pagila  Cannot start service pagila: driver failed programming external connectivity on endpoint pagila (d9d4eba18cc6c325d45fa6c1ba4b23a122ef1b1dcf3a85d4370d1315c840ad6c): Error starting userland proxy: error while calling PortManager.AddPort(): listen tcp4 0.0.0.0:5432: bind: address already in use

ERROR: for pgadmin  Cannot start service pgadmin: driver failed programming external connectivity on endpoint pgadmin4_container (f048adfe023e7821b17cd1f8b9c47ca8135c644db3461973712a0f6d192f4a61): Error starting userland proxy: error while calling PortManager.AddPort(): listen tcp4 0.0.0.0:5050: bind: address already in use

ERROR: for pagila  Cannot start service pagila: driver failed programming external connectivity on endpoint pagila (d9d4eba18cc6c325d45fa6c1ba4b23a122ef1b1dcf3a85d4370d1315c840ad6c): Error starting userland proxy: error while calling PortManager.AddPort(): listen tcp4 0.0.0.0:5432: bind: address already in use
ERROR: Encountered errors while bringing up the project.
```
Because it says that it has to do with ports already being in use, I decided to change the number 5432 to 6272, a random number, in the docker-compose.yml file as well as the 5050 port to 6273, another random number. This allowed my docker containers to successfully run, but I cannot get access to postgres now. 

Did anyone else encounter this when getting set up? If so, how were you able to resolve it? Any help is greatly appreciated--thanks!

**Comment by GusAlbach** [comment]
HI @epaisano 
Are you sure your brought down your previous containers before attempting to rebuild them?

**Comment by epaisano** [comment]
@GusAlbach yep, I ran 
```
docker stop <hash>
```
and then ran
```
docker ps
```
to ensure nothing was running before rebuilding.

**Comment by GusAlbach** [comment]
is your directory 
```
~/pagila-hw3/pagila
```
I had a similar error when I attempted to build the containers from this location rather than `~/pagila-hw3`. I didn't change any ports, but once I ensured previous containers were down and changed my directory I got it working.

**Comment by epaisano** [comment]
@GusAlbach yep, when I run it from ~/pagila-hw3 it builds successfully, but I don't get the new data, only the two rows from the store and staff columns

**Comment by GusAlbach** [comment]
Hmmm... you may want to check that all containers are down from `~/pagila-hw3` , I think I found that bringing the containers down from `~/pagila-hw3/pagila` didn't actually bring down every container and I had to ensure they were all down from `~/pagila-hw3` before I got access to the new data

**Comment by epaisano** [comment]
@GusAlbach I got it to work! I had to run 
```
docker rm $(docker ps -qa)
```
to actually remove all of them. Thank you so much!!!
