### ISSUE TITLE
how to download file from lambda server to local in order to submit to sakai 

### ISSUE THREAD

**Issue by giffiecode** [mikeizbicki/cmc-csci143#476]
After playing around with it, I try to use `scp -P 5050 Yuechen.Pei.23@lambda-server:~/lab-transactions/Ledger/__init__.py Desktop` to download the file to my local in order to upload to sakai. However, it gives me the error: `ssh: connect to host lambda-server port 5050: Connection refused` 

how to download the file / upload the file to sakai?

**Comment by giffiecode** [comment]
I temporarily solved this issue by pushing it to github and download. However, would love to know how to do the download from server if possible

**Comment by luisgomez214** [comment]
I used 
`scp -P 5055 Luis.Gomez.25@lambda.compute.cmc.edu:~/bigdata/lab-transactions/Ledger/__init__.py ~/Downloads
`
and it worked
