### ISSUE TITLE
Disk Quota Exceeded Error

### ISSUE THREAD

**Issue by AvidThinkerArsum** [mikeizbicki/cmc-csci143#488]
Hi Everyone,

I'm getting a 'Disk Quota Exceeded Error' as I'm working on the lambda server. I got this when I was trying to clone a file. I think folks have had this in the past but I can't figure the way around it. Any leads on this?

**Comment by eoinoconnell04** [comment]
Here is an explanation of how to resolve it:
https://github.com/mikeizbicki/cmc-csci143/issues/459#issuecomment-1965777236

You need to see which files are taking up lots of space and then delete them.
