### ISSUE TITLE
Host already in use error but no containers are running

### ISSUE THREAD

**Issue by justinchiao** [mikeizbicki/cmc-csci143#489]
```
Creating twitter_postgres_pg_normalized_1 ...
Creating twitter_postgres_pg_normalized_1   ... error
WARNING: Host is already in use by another container
```

Like the title says, I have brought down and removed all my containers but still getting this error. I'm using 1317 and I'm wondering if maybe some else in the class has accidentally used my id or if its something in my docker-compose.yml.

**Comment by mikeizbicki** [comment]
In order to help you, I would need to see the actual command you ran and the output of `docker ps -a`.

**Comment by justinchiao** [comment]
Silly mistake, flipped my exposed port and container port
