### ISSUE TITLE
Problems with the time command in the load_tweets_sequential.sh file

### ISSUE THREAD

**Issue by henrylong612** [mikeizbicki/cmc-csci143#492]
For the twitter_postgres_parallel homework, is anyone else running into issues with the `time` command in the `load_tweets_sequential.sh` file? Whenever I try to run the file with the time commands, I get 

```
$ sh load_tweets_sequential.sh
================================================================================
load denormalized
================================================================================
time: cannot run for: No such file or directory
Command exited with non-zero status 127
0.00user 0.00system 0:00.00elapsed ?%CPU (0avgtext+0avgdata 1116maxresident)k
0inputs+0outputs (0major+27minor)pagefaults 0swaps
COPY 0
load_tweets_sequential.sh: 11: load_tweets_sequential.sh: Syntax error: "done" unexpected
```

When I remove the `time` commands from in front of the for loop, this error goes away. Additionally, if I run actual code of the `load_tweets_sequential.sh` file on the command line, I get no errors. It seems that this is also causing errors in the GitHub tests.

Anyone have any guidance?

**Comment by abizermamnoon** [comment]
Try 

```
./load_tweets_sequential.sh
```
The file is a bash file not an sh file

**Comment by henrylong612** [comment]
Thank you @abizermamnoon! That worked!

**Comment by abizermamnoon** [comment]
Can you send me the error message you get on github? I think all the test cases are linked somehow
