### ISSUE TITLE
NULL Character while inputting into the Normalized DB

### ISSUE THREAD

**Issue by saatvik7** [mikeizbicki/cmc-csci143#50]
So, when I run the python file to input the data into the Normalized DB, it works perfectly for the first 9000 tweets; however, in the last 1000, I get the following error. 
<img width="892" alt="Screenshot 2021-03-28 at 8 31 47 PM" src="https://user-images.githubusercontent.com/60725683/112756930-0818a080-9005-11eb-979b-d5f1f4005d8a.png">
And this is not actually a problem with the `source` field as stated in the error as even if I get rid of it, the error persists. Is there something we are supposed to do to filter out these NULL characters? I have tried some things but none of them seem to be working. Thank you!

**Comment by saatvik7** [comment]
I also tried using the `remove_nulls` function on the fields that are giving these errors; however, I am still getting the same error.

**Comment by nguyenank** [comment]
I remember I got this error; I think what I found was that the error message line doesn't actually point to the exact field; it just always points to like the last line in your `execute`? I think when I just called `remove_nulls` on absolutely every field that could have a null then it worked fine.

**Comment by saatvik7** [comment]
Yup, I just tried this and it works!
