### ISSUE TITLE
Running load_tweets script error (could not connect to server)

### ISSUE THREAD

**Issue by amytam01** [mikeizbicki/cmc-csci143#51]
Hi there! Curtis and I are facing the same issue, any help would be appreciated. Thank you :)
<img width="890" alt="Screen Shot 2021-03-28 at 2 04 53 PM" src="https://user-images.githubusercontent.com/38165346/112767994-932a7400-8fce-11eb-9cd7-1826050fb695.png">

**Comment by amytam01** [comment]
Resolved! I had port issues

**Comment by ejarquin22** [comment]
Can you explain what you did to resolve your port issue? I might be having the same one.

**Comment by amytam01** [comment]
> Can you explain what you did to resolve your port issue? I might be having the same one.

My port numbers weren't the same in the docker port and my script :)
