### ISSUE TITLE
Kill issue

### ISSUE THREAD

**Issue by danzhechen** [mikeizbicki/cmc-csci143#517]
Hey there, 

I am currently facing an issue with kill. I try to run the shell to import the data. I thought there were some issues and the code exits. But there seems one of the time it keeps running. I ran `ps` to exam the processes, which is clear. But when I ran `ps -a`, there are many python and psql and sh running. If I want to kill them and restart my life, what might be an appropriate approach? I tried something brutal like `pkill psql` or `ps aux | grep your_command_name | awk '{print $2}' | xargs kill -9`, but it all says operation not permitted. So what could be a proper way to stop that? At the moment, I might just wait it to finish, but I wonder how could I simply just do a small test and restart it?

**Comment by danzhechen** [comment]
When I run `ps -a`, I got this 
```
  PID TTY          TIME CMD
13008 ?        00:00:00 sh
13009 ?        00:00:00 pager
24228 pts/14   00:00:00 vim
40947 ?        12:43:48 python
48453 pts/5    00:00:00 sh
48454 pts/5    00:00:00 pager
60214 pts/1    00:00:00 sh
60215 pts/1    00:00:00 pager
75163 pts/5    00:00:00 ps
``` 
The strange thing is that there is no way for me to kill the python. And the running time seems strange to me. It only advances for a few seconds or minutes when in real life it passes half an hour. Is this okay? 

Because right now when I run my `docker ps -a` command, there is still a issue with the normalized database
```
bd3fe6dd5b8e   twitter_postgres_indexes_pg_normalized_batch   "docker-entrypoint.s…"   10 hours ago   Exited (2) 10 seconds ago                                               twitter_postgres_indexes_pg_normalized_batch_1
```

**Comment by mikeizbicki** [comment]
I've deleted the folders as requested over email.  If this is still a problem, I'll need to take a look in person.
