### ISSUE TITLE
My baby is here (and changes to this week's schedule)

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/cmc-csci143#52]
My wife has gone into labor, and so I'm helping her deliver a baby :)  I won't be available for class or office hours on Monday (Mar 29), so they're both cancelled.  We should have class/office hours on Wednesday (Mar 31) like normal.

Since I won't be available for homework questions like normal on Monday, I will give everyone a blanket extension on the homework until Thursday at midnight.  This will give you a chance to ask any questions on Wednesday, and still have some time to work on the assignment.

**Comment by ejarquin22** [comment]
Congrats on your wife going into labor! Hope all goes well. But you are referring to the twitter_postgres homework, right?

**Comment by BrandontMitchell** [comment]
Congratulations!

**Comment by amytam01** [comment]
Congratulations! Stay safe and we all wish you and your wife (and baby!) the best :)

**Comment by mikeizbicki** [comment]
Good morning, everyone.  We'll have class today like normal.

Here's some baby pictures:

![isaac2](https://user-images.githubusercontent.com/1052630/113160555-73739580-91f2-11eb-85e0-6ddb6d2683d2.jpg)

![isaac1](https://user-images.githubusercontent.com/1052630/113160742-9b62f900-91f2-11eb-9bb5-d56ee2041744.jpg)

PS.  People often talk about the great salaries that CS/DS majors can earn at FAANG companies.  They don't talk as much, however, about the great benefits, such as parental leave.  Every major tech company has a [generous parental leave policy](https://www.vox.com/2018/1/31/16944976/new-parents-tech-companies-google-hp-facebook-twitter-netflix), with companies like netflix offering a full year of paid time off for both mothers and fathers.

PPS.  Since today is [César Chávez day](https://en.wikipedia.org/wiki/Cesar_Chavez_Day), which celebrates Chávez's work for labor right, I feel obligated to also point out that [tech companies have been illegally colluding to reduce employee compensation](https://en.wikipedia.org/wiki/High-Tech_Employee_Antitrust_Litigation).  The work of Chávez and others like him have helped ensure that employees get fair wages and fair parental leaves, whether they be low-skill or hi-tech workers.

**Comment by mikeizbicki** [comment]
@ejarquin22 Yes, the twitter_postgres assignment deadline is extended until Thursday.
