### ISSUE TITLE
Test case command no longer running

### ISSUE THREAD

**Issue by amyyu116** [mikeizbicki/cmc-csci143#541]
Hi, 

I was originally able to get the command ``time docker-compose exec pg_normalized_batch   ./check_answers.sh sql.normalized_batch`` provided to us to work, and it would pass in like 2 seconds after I added some indexes, but I'm currently working on the denormalized part of the indexes homework and I've found that the time + shell commands are no longer working even though I don't think I've made any changes recently. 

```ayu6593b@lambda-server:~/twitter_postgres_indexes$ docker-compose exec pg_normalized_batch psql
/home/ayu6593b/.local/lib/python3.6/site-packages/paramiko/transport.py:32: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography will remove support for Python 3.6.
  from cryptography.hazmat.backends import default_backend
psql (16.2 (Debian 16.2-1.pgdg110+2))
Type "help" for help.

postgres=#
\q
```
^^ Here I'm able to access the database, but then just the terminal time/shell commands that don't work. Here is what happens when I run the time command now:
```
ayu6593b@lambda-server:~/twitter_postgres_indexes$ time docker-compose exec pg_normalized_batch   ./check_answers.sh sql.normalized_batch
/home/ayu6593b/.local/lib/python3.6/site-packages/paramiko/transport.py:32: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography will remove support for Python 3.6.
  from cryptography.hazmat.backends import default_backend
OCI runtime exec failed: exec failed: unable to start container process: exec: "./check_answers.sh": stat ./check_answers.sh: no such file or directory: unknown

real    0m0.720s
user    0m0.594s
sys     0m0.398s```

**Comment by mikeizbicki** [comment]
I believe the script is called `run_tests.sh`, but you are using `check_answers.sh`.  Changing your command should fix the problem.

The `check_answers.sh` filename was used in a previous semester's version of the assignment.  If you found that command still referenced somewhere, I would appreciate a pr correcting my mistake.

**Comment by amyyu116** [comment]
Ok I can't find where I got this command anymore but that makes a lot of sense. Thank you!
