### ISSUE TITLE
Loading tweets issue 

### ISSUE THREAD

**Issue by Asanchez2112** [mikeizbicki/cmc-csci143#57]
Hello, 
I am trying to load the data via load_tweets.sh, however, I get an error saying that the file containing the tweets doesn't exist. At first, I thought I had a type or the path may have been incorrect, but when I went to the data-fast folder myself, I saw that it was empty and I am not sure how to fix that or if maybe the tweet files are located somewhere else? Any help would be appreciated
<img width="627" alt="cs1431" src="https://user-images.githubusercontent.com/50669999/115789331-970da400-a38a-11eb-9334-f3a87f764c4b.PNG">
<img width="611" alt="cs1432" src="https://user-images.githubusercontent.com/50669999/115789333-97a63a80-a38a-11eb-9f37-12faa3adf391.PNG">

**Comment by saatvik7** [comment]
Yeah, the data-fast folder is empty for some reason, but all the tweets are also located in the data/'Twitter dataset' folder. You can just change the directory to that and it should work fine!

**Comment by mikeizbicki** [comment]
Sorry, the files got deleted when cleaning up some disk space.  I've re-added the `/data-fast/twitter 2020/geoTwitter20-04-01.zip` file, so the script should run as-is.

**Comment by Asanchez2112** [comment]
Thank You!!!!
