### ISSUE TITLE
Problems when running queries on the denormalized database

### ISSUE THREAD

**Issue by saatvik7** [mikeizbicki/cmc-csci143#58]
When I'm running the following query:

`SELECT COUNT(DISTINCT data->>'id')  FROM tweets_jsonb WHERE ((data -> 'entities'::text) -> 'hashtags'::text)  @> '{"text":"coronavirus"}';`

I'm getting the count as 0 and I have no idea why. Any help would be appreciated!

**Comment by nguyenank** [comment]
`hashtags` is a list; so you want to see if it contains something of the form `[{"text":"coronavirus"}]`.

**Comment by saatvik7** [comment]
Okay, now I'm getting a count but it's nearly half the number it's supposed to be.

**Comment by nguyenank** [comment]
Yeah so I would recommend checking out the schema for the denormalized database, especially the views (which I don't really understand but heard we will?), they are very helpful for figuring out how the data is structured (and what is relevant).

**Comment by saatvik7** [comment]
Alright, I'll try that. Thanks!
