### ISSUE TITLE
Failed to create new OS thread

### ISSUE THREAD

**Issue by amytam01** [mikeizbicki/cmc-csci143#59]
Running `$ time docker-compose exec pg_denormalized ./check_answers.sh sql.denormalized`
and I ran into a problem where I got `runtime: failed to create new OS thread (have 13 already; errno=11)
runtime: may need to increase max user processes (ulimit -u)
fatal error: newosproc`

How do I delete old OS threads? Or what should I do to fix this issue so that I can continue checking my answers? Thanks!

<img width="641" alt="Screen Shot 2021-04-25 at 5 22 30 PM" src="https://user-images.githubusercontent.com/38165346/116014646-1ac5cb80-a5eb-11eb-89d9-59121ac36c9d.png">

**Comment by mikeizbicki** [comment]
Closing because we solved this on zoom.
