### ISSUE TITLE
Lab this week

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/cmc-csci143#6]
I'm not going to be able to make the 10-11am lab time this week because I'm a speaker at a CMC event on algorithmic bias.  If you'd like to have lab this week, then reply to this message with a suggested time.  (See [my calendar](https://izbicki.me/schedule.html) to ensure that I'm free too.)  We'll do whatever time has a consensus.

**Comment by amytam01** [comment]
Friday night (since Friday 10-11 doesn't work)?

**Comment by mikeizbicki** [comment]
I'm free Friday 2-3pm and 4-5pm, but I can't do any later.  Does anyone have a preference between those times?

**Comment by lsanders99** [comment]
I would prefer 4-5pm (can't make 2-3pm)

**Comment by mikeizbicki** [comment]
Okay, let's do 4-5pm tomorrow (Friday).  See you then :)
