### ISSUE TITLE
Password Authentication Failed for User "Novichenko"

### ISSUE THREAD

**Issue by nguyenank** [mikeizbicki/cmc-csci143#62]
I did Task 0 and 1 on the `search_engine` homework and things worked relatively fine; I vaguely remember getting issues with password authentication but they cleared up after I brought the containers down and then back up I think. However, I realized I accidentally deleted some files and needed to move the whole repo anyways and generally mucked things up enough that I was pretty sure I needed to start from scratch, so I deleted all of the containers and all of the images they used (which I don't think was my best idea, but here we are) and repeated steps Task 0 and 1 on my new clone (which did involve generating a new production password, if that's relevant), but now I cannot get around the password authentication failing, which is most evident when I try to access the webpage on my browser and that error pops up. All of the script checks still pass perfectly.

**Comment by afzal-p** [comment]
I am receiving the same error. Have you figured out why password authentication is failing?

**Comment by mikeizbicki** [comment]
Without seeing the actual commands you've run and the error messages, it's difficult to figure out what the problem might be.

My first recommendation is to try the fix @asapirstein had for #63 and make sure that the `.env.prod` file is setup correctly, but if that doesn't work then it's probably something that's most easily fixed over zoom.

**Comment by nguyenank** [comment]
I resolved this by basically trying again by, in `docker-compose.yml`, changing the `volumes` from  `$HOME/bigdata/search_engine:...` to `$HOME/bigdata/search_engine2:...` so it would create a new volume and this one worked.

**Comment by afzal-p** [comment]
> I resolved this by basically trying again by, in `docker-compose.yml`, changing the `volumes` from `$HOME/bigdata/search_engine:...` to `$HOME/bigdata/search_engine2:...` so it would create a new volume and this one worked.

This solution worked, thank you!
