### ISSUE TITLE
Issue Opening in Localhost (Task 1 in search engine)

### ISSUE THREAD

**Issue by hwing777** [mikeizbicki/cmc-csci143#63]
I'm trying to get started with the search engine, and I got through most of Task 1 but am getting an issue with opening the page in Firefox. I'm getting an error 'sqlalchemy.exc.OperationalError', and I don't know what issue is. All of the checks in `check_web_endpoints.sh` pass, and I'm pretty sure my port forwarding is connected properly.
![Screenshot 2021-04-28 002722](https://user-images.githubusercontent.com/39741440/116346566-8b6e1300-a7b8-11eb-9aac-e9cf82f2025e.png)

**Comment by asapirstein** [comment]
I was getting the same issue and worked with Mike on this after class, for me it was that I never initialized the submodules: 
```
git submodule init 
git submodule update
``` 
fixed the problem for me.
