### ISSUE TITLE
Small Fix For Task 2b

### ISSUE THREAD

**Issue by nguyenank** [mikeizbicki/cmc-csci143#67]
On step 3 of Task 2b, it says to run the command
```
$ .downloader_host.sh "$HOST/*"
```
to insert urls from 5 hostnames. I think this should just be
```
$ .downloader_host.sh "$HOST"
```
because `/*` is appended  in the `downloader_host.sh` script.

**Comment by mikeizbicki** [comment]
Yes, this is correct.  Fixed in 8c7b990 .
