### ISSUE TITLE
Stopped Task 2b Insertion Early

### ISSUE THREAD

**Issue by nguyenank** [mikeizbicki/cmc-csci143#69]
So I completed most of Task 2b and had my 5 containers for inserting urls from 5 hostnames running, but I think by exiting the lambda server and then logging on again a few hours later, that login exited all of my containers (that, or I have miraculous timing, given my remaining 4 containers all exited exactly 23 seconds before I ran `docker ps` on the second login, but I highly highly doubt that). Based on the logs I don't think any of the containers were done running and `downloader_host.py` prevents running the same hostname twice. While debugging I did get rid of those containers, but I don't think there was anyway to restart them anyways. Is that fine, or should I repeat the process with different hostnames, or something else?

**Comment by mikeizbicki** [comment]
As long as you have a couple thousand urls from the hosts you were downloading from, then you'll be fine from a grading perspective, and don't need to rerun anything.  More urls would obviously result in better results in the search engine, but you won't be graded on exhaustively downloading everything from the host.
