### ISSUE TITLE
Task 2a: building docker container

### ISSUE THREAD

**Issue by afzal-p** [mikeizbicki/cmc-csci143#70]
I am running:
`./downloader_warc.sh https://commoncrawl.s3.amazonaws.com/crawl-data/CC-MAIN-2021-17/warc.paths.gz`

and see the following output indicating the container is built:
<img width="830" alt="Screen Shot 2021-05-03 at 1 48 47 PM" src="https://user-images.githubusercontent.com/36056734/116919025-50d00480-ac16-11eb-9484-8161bbf143a4.png">

However when I go to verify the container is running:
<img width="1641" alt="Screen Shot 2021-05-03 at 1 49 52 PM" src="https://user-images.githubusercontent.com/36056734/116919118-72c98700-ac16-11eb-8d3e-cd1c035b87d8.png">
Status shows: `Exited (0) About a minute ago`
 I tried to check docker logs, but the command isn't doing anything:
<img width="1390" alt="Screen Shot 2021-05-03 at 1 51 13 PM" src="https://user-images.githubusercontent.com/36056734/116919323-ba501300-ac16-11eb-81f0-c3df6a8d19fd.png">

Any ideas to determine what is going wrong?

**Comment by cschulz21** [comment]
You can run the line `docker logs $container_id` to see the log from the container. 

My best guess is that you are getting a 404 error. The links I used looked like `/downloader_warc.sh https://commoncrawl.s3.amazonaws.com/crawl-data/CC-MAIN-2020-34/segments/1596439735792.85/warc/CC-MAIN-20200803083123-20200803113123-00000.warc.gz`. This can be found by clicking on the month year on the common crawl. Then you can download the WARC paths (ex 'CC-MAIN-2020-50/warc.paths.gz') and open the downloaded file using vim to get a list of URLs

**Comment by afzal-p** [comment]
Thank you, I was able to get the container running and view the logs:

<img width="1423" alt="Screen Shot 2021-05-03 at 2 28 09 PM" src="https://user-images.githubusercontent.com/36056734/116923200-f5087a00-ac1b-11eb-8ba0-09d8cd3ed2b3.png">

Has anyone encountered these warnings in their logs?
