### ISSUE TITLE
/ngrams?query=trump Failing and errors while downloading WARC file

### ISSUE THREAD

**Issue by saatvik7** [mikeizbicki/cmc-csci143#73]
Previously I was able to pass all the tests but now, the /ngrams?query=trump fails. 

Furthermore, when I'm trying to download the WARC file using this link: https://commoncrawl.s3.amazonaws.com/crawl-data/CC-MAIN-2018-34/segments/1534221219692.98/warc/CC-MAIN-20180822065454-20180822085454-00702.warc.gz
I'm getting the following error when I look at the docker logs for the container that was created. I'm quite sure that my link is valid as it's downloading the file when I paste it into the browser. Any help would be greatly appreciated!
<img width="1232" alt="Screenshot 2021-05-07 at 12 50 57 PM" src="https://user-images.githubusercontent.com/60725683/117501687-3e660b80-af33-11eb-93c5-22ba1ba3fd35.png">

**Comment by saatvik7** [comment]
Is there a way I can reset all the volumes on my account because it seems as though the volumes stored in the `bigdata` folder are inaccessible and I'm also not being to manually delete those folders. Basically what I'm trying to do is get a clean slate because there are a lot of issues popping up.

**Comment by nguyenank** [comment]
In `docker-compose.yml` I think, rename the bit of the volume from `bigdata` to `bigdata2` or something and rerun. I have more clear directions in another issue I open ~1 week ago, but that's the gist of how you can essentially restart.

**Comment by saatvik7** [comment]
Okay, I used a clean slate and it works now.
