### ISSUE TITLE
How long should we let the host_downloader run for?

### ISSUE THREAD

**Issue by saatvik7** [mikeizbicki/cmc-csci143#78]
My `host_downloader` has been running for over a day and has gathered over 1 Million web pages so far across the five hosts I had provided, and it seems like it's going to keep running for a while. Should I wait for it finish, or stop it early?

**Comment by mikeizbicki** [comment]
It's fine to stop it early.  I don't have any hard numbers in mind about how many urls need to get downloaded, just enough that it's clear it ran for a while.
