### ISSUE TITLE
Keeping our lambda server accounts

### ISSUE THREAD

**Issue by anan-ara** [mikeizbicki/cmc-csci143#79]
Is there anything we have to do to keep our lambda server accounts active after this semester?

**Comment by mikeizbicki** [comment]
I'm happy to let you keep the accounts.  I have some admin stuff I need to do this week (and maybe next week) which will require me to temporarily disable all your accounts though.  Once I've finished with that, I'll post an issue here letting you know, and then I'll reenable anyone's account that would like it.

**Comment by mikeizbicki** [comment]
I've disabled everyone's lambda server accounts, except for those people who have asked to keep them open.  If I missed anyone, or there's any problems, let me know and I'll try to fix them.
