### ISSUE TITLE
"Disk Quota Exceeded" 

### ISSUE THREAD

**Issue by cduong21** [mikeizbicki/cmc-csci143#8]
I'm attempting to do the lab for this week, but I've run into this error `bash: cannot create temp file for here-document: Disk quota exceeded`. Do you have any advice for how to clear some space up through the command line. (I'm unable to save anything I've edited in the files) 

Thank you!

**Comment by mikeizbicki** [comment]
The command
```
$ du -hd1
```
will show you the disk usage of all the folders in your working directory.  You can then use `rm -rf` to delete the big folders that you don't need anymore.
