### ISSUE TITLE
Final grade posted

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/cmc-csci143#80]
I've graded everyone's final exams and entered the results in sakai.  The median score was a 31/40 (77%), and there were 4 scores greater than 100%.  I left detailed notes about which problems you missed in sakai, and I've posted the answer key so that you can compare them and verify that I did not make a mistake: https://github.com/mikeizbicki/cmc-csci143/blob/2021spring/final/final-key.pdf

The grade that you have in sakai is the grade that I'll be entering for you.  I'll be entering your grades into the portal on Wednesday, so you have until then to check your grade and make sure I haven't made any mistakes.

A few of you are <3 points away from the next higher letter grade.  By default, I won't be "rounding up", but I'll give you all one last chance at some extra credit.  You can get up to 3 points of extra credit by:
* Selecting a video from [pgcon 2020](https://www.youtube.com/playlist?list=PLuJmmKtsV1dP8IGGH6Z_sYQKxfDqtoSLj) that looks interesting to you, watching it, and emailing me 5 things you learned from the video.
* Each video you do this for will be worth +1 point.

---

It was a pleasure to have you all in class this semester for big data.  For those of you graduating this semester, congratulations!  And for those of you coming back next fall, I look forward to seeing you all in person again :)

If there's ever anything I can do to help you in the future, please don't hesitate to ask.

-- Mike

**Comment by saatvik7** [comment]
Thank you so much for being such an awesome Prof., I really enjoyed taking this class! 

I had a quick question. I can't see a grade on Sakai, what should I do to see it?

**Comment by mikeizbicki** [comment]
It looks like I hadn't made the letter grade column visible in the gradebook before, but I think I just fixed that so you should be able to see it now.

**Comment by anan-ara** [comment]
Thank you prof! I learned so much from this class. This is definitely the best class I've taken since I've come to college!
