### ISSUE TITLE
Meet and Greet Thread

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/cmc-csci143#83]
Welcome to big data!

In this thread, we'll all introduce ourselves and practice using github issues.  We'll be using github issues for all our in-class communication, so it's important that you understand how the system works.  In particular, you need to understand [github's markdown formatting syntax](https://guides.github.com/features/mastering-markdown/).

To practice, please reply to this post with:
1. your name (including what you'd like me to call you if it's different than in sakai)
1. your favorite food highlighted in **bold** and
1. a quote you like placed inside a code block

**Comment by mikeizbicki** [comment]
Hi everyone,

Please call me Mike.  I've been drinking a lot of **chocolate tea** this winter, and I'll give you two fun quotes:
```
UNIX is basically a simple operating system, but you have to be a genius to understand the simplicity.
  --  Dennis Ritchie (co-inventer of UNIX)

If you have any trouble sounding condescending, find a UNIX user to show you how it's done.
  --  Scott Adams (Dilbert Cartoonist)
```

**Comment by DestrosCMC** [comment]
Hi Everyone, 

My name is Kieran. My favorite drink right now is **green tea** and here is an interesting quote:

```
I'm the type of person who loves to stay busy, even in my off-season. - Eli Manning
```

**Comment by msanluis** [comment]
Hi everyone,

My name is Matt. My favorite food is **poke** and my quote is:

```
A ship is always safe at shore, but that is not what it's built for - Albert Einstein
```

**Comment by edwardwu11** [comment]
Hi all,

My name is Eddy. My favorite food is **ribeye steak** and my favorite quote is:
```
You miss 100% of the shots you don't take. - Wayne Gretzky
```

**Comment by Tcintra** [comment]
Hi everyone,

My name is Thomas, my favorite food is **udon** and one of my favorite quotes is:

```
The ships hung in the sky in much the same way that bricks don't. - Douglas Adams
```

**Comment by RuiluGao** [comment]
Hi everyone,

My name is Lulu, my favorite food is **Chinese hotpot** and my favorite quote is:

```
Cogito, ergo sum. -- René Descartes
```

The quote is in Latin which translates into:

```
I think, therefore I am.
```

**Comment by dustin-lind** [comment]
Hi everyone,

My name is Dustin. My favorite food is **burritos** from this place called Mr. Burritos.

My favorite quote is:
```
Fortune favors the brave
```
That Crypto.com commercial got me...

**Comment by mikeizbicki** [comment]
@Tcintra @RuiluGao @dustin-lind: Your quotes are rendered incorrectly.  You should put it inside of a code block
```
like this
```
not an inline code element `like this`.  In general, it is always bad style to have inline code elements on a line by themselves.

Please update your replies to fix this issue.

**Comment by joeybodoia** [comment]
Hi everyone,

My name is Joey. My favorite food is **chicken katsu**, particularly from L&L Hawaiian Barbecue.

A quote I enjoy:
```
If I had a gun with two bullets and I was in a room with Hitler, Bin Laden, and Toby, I would shoot Toby twice.
-- Michael Scott
```

**Comment by axelahdritz** [comment]
Hey guys! 

My name is Axel. My favorite food is **tiramisu**. 

Lovely little thing written in Ionesco's journal, upon witnessing the birth of a child:
```
"Not everything is unsayable in words, only the living truth." -- Eugène Ionesco
```

**Comment by Bhargavaa1** [comment]
Hi team!
My name is Adi Bhargava and my favorite drink right now is  **boba tea**. A quote that I enjoy and will rely on this semester is 
```
"Fail early, Fail often."-Mark Kampe
```

**Comment by ohorban** [comment]
Hi everyone, I am Alex. My favorite food is **Bulgogi**. 
```
"You don't become a billionaire when you earn a billion dollars. You become a billionaire when you change the lives of a billion people"
```

**Comment by vbopardi** [comment]
Hi everyone. I'm Varun Bopardikar and my favorite food is **nachos**. A quote I like is by Teddy Roosevelt:

```
It is not the critic who counts; not the man who points out how the strong man stumbles, or where the doer of deeds could have done them better. The credit belongs to the man who is actually in the arena, whose face is marred by dust and sweat and blood; who strives valiantly; who errs, who comes short again and again, because there is no effort without error and shortcoming; but who does actually strive to do the deeds; who knows great enthusiasms, the great devotions; who spends himself in a worthy cause; who at the best knows in the end the triumph of high achievement, and who at the worst, if he fails, at least fails while daring greatly, so that his place shall never be with those cold and timid souls who neither know victory nor defeat. 
```

**Comment by afroCoderHanane** [comment]
Hi everyone, I am hanane. My favorite food is plaintain+steak.
A quote I like is : 

```
Every morning in Africa, a gazelle wakes up, it knows it must outrun the fastest lion or it will be killed. Every morning in Africa, a lion wakes up. It knows it must run faster than the slowest gazelle, or it will starve. It doesn't matter whether you're the lion or a gazelle-when the sun comes up, you'd better be running. -- Christopher McDougall
```

**Comment by Tonnpo** [comment]
Hi everyone,

I am Ton. My favorite drink is **sea salt caramel coffee** especially from 85. The quote I really like is
```
Life is like the Krebs cycle. I don't know the Krebs cycle.
```

**Comment by anyu-yu** [comment]
Hello everyone,

My name is Andrew. One of my favorite foods is **udon**. A quote that I like is:
```
The wave returns to the Ocean
(From The Good Place)
```

**Comment by erdsal4** [comment]
Hello everyone,

My name is Salih. My favorite drink is **black tea**. A quote that I like is:

```
Desires make slaves out of kings and patience makes kings out of slaves. 
```

**Comment by jzlilili** [comment]
Hello everyone,
I'm Jennifer, one of my favorite foods is **sushi**, and a quote that I like is:
```
We don't make mistakes, just happy little accidents.
```

**Comment by katiewu71** [comment]
Hi everyone!

My name is Katie. My go-to drink is currently a **hazelnut latte** and I also love **fried chicken**. Here’s my favorite funny quote: 

```
“Why waste time say lot word when few word do trick” -Kevin Malone.
```

**Comment by cristywei** [comment]
Hi everyone,

My name is Cristy. My favorite food is **coffee ice cream**. A quote that I like is:

````
"You must have chaos within you to give birth to a dancing star."
````

**Comment by leafsphere** [comment]
Hi!

My name is Julie, and my favorite food is **jelly**. A quote I enjoy is:
```
"To live is the rarest thing in the world. Most people exist, that is all." -Oscar Wilde
```

**Comment by yilinli22** [comment]
Hi everyone.

My name is Yilin. My favorite food is **egg tart**. A quote I enjoy is:

```
"Forever is composed of nows." - Emily Dickinson
```

**Comment by Luew2** [comment]
Hello!

My name is Lucas. My favorite food is **Meatloaf** and a quote I like is:

```
“Rivers know this: There is no hurry. We shall get there some day.”
—Winnie the Pooh
```

**Comment by dabalus** [comment]
My name is Daniel Abalusi and my favorite food is **rice and chicken**. My favorite quote is

```
“A dream is what makes people love life even when it is painful”
—Theodore Zeldin
```

**Comment by AvnikaG** [comment]
Hi! My name is Avnika but I go by Avi (the "A" pronounced like in "Abby").  My favourite food at the moment is **kimbap or satay** and a quote I like is 

` "Motivation is what gets you started. Habit is what keeps you going"  - not sure who it is by! `

**Comment by yurynamgung** [comment]
Hi my name is Yury Namgung and my favorite food is **sushi**. A quote I like is 

```
Life is what happens when you're busy making other plans. -John Lennon
```

**Comment by alex-muehleisen** [comment]
Hi everyone,

My name is Alex. My favorite food is **pasta**.  A quote I like is:

```
"Everyone is a genius. But if you judge a fish by its ability to climb a tree, it will live its whole life believing that it is stupid."

```

**Comment by samcbogen** [comment]
I did not realize this did not post until someone told me, but my name is Sam, and my favorite food is **Sushi**. A great quote is:

`There may be people who have more talent than you, but there's no excuse for anyone to work harder than you do - and I believe that.` - Derek Jeter
