### ISSUE TITLE
Extra Credit Tasks

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/cmc-csci143#85]
There will be a handful of opportunities for extra credit throughout the semester, and I'll post the details here.

**Comment by mikeizbicki** [comment]
If you see a mistake anywhere in the github repo, submit a pull request with the correction.  You will get 1 point of extra credit for the first accepted pull request.  Subsequent pull requests may earn slightly less.

**Comment by mikeizbicki** [comment]
If you install linux on your personal computer and use it throughout the semester, you will get 1 point of extra credit.  Any distro is fine.  I personally like [Debian](https://www.debian.org/distrib/) the best because it has a strong open source philosophy and is very stable.  Another popular choice is Ubuntu, which is a debian fork that incorporates some proprietary binary packages.  All the cool kids are using Arch Linux these days.

**Comment by iamasteriix** [comment]
Does WSL Ubuntu count?

**Comment by mikeizbicki** [comment]
@ceejay-el Good question.  Virtual machine/WSL installs do not count.  You must be booting directly into Linux.  This forces you to think about things like partitioning schemes and boot managers, and I want it to be relatively inconvenient to switch back into windows so that you're forced to do more things in linux.
