### ISSUE TITLE
Putty Lambda Server Login Error

### ISSUE THREAD

**Issue by edwardwu11** [mikeizbicki/cmc-csci143#88]
Hi Mike,

I hope you are doing well! I had a question about setting up the Lambda Server. I was able to successfully install Putty for Windows, but after I put in the correct IP Address and Port, I kept getting a blank screen saying ```Network Error: Connection Timed Out```. Please let me know how I can fix this issue and thanks for your help.

Best,
Edward

**Comment by mikeizbicki** [comment]
Hmm.... I just checked and the server is up just fine right now.  The most likely issue is that somehow putty's settings aren't setup quite right.  It might also be that you have some sort of antivirus/firewall program blocking the connection, but I think that's unlikely.

I'll be on zoom starting an hour before our next class on Friday (i.e. starting at 10AM).  If you don't get the issue resolved before then, you could log into zoom and we could work it out then.
