### ISSUE TITLE
Lab Q3 part i

### ISSUE THREAD

**Issue by erdsal4** [mikeizbicki/cmc-csci143#91]
I couldn't get the `finger` command to give me information about all the times that `mizbicki` has logged onto the server. Currently it only displays info about its last login. Are there any tips on how to achieve that?

**Comment by mikeizbicki** [comment]
My guess is that you ran the command
```
$ finger mizbicki
```
And you're right that that command doesn't work.  Instead, run `finger` without any arguments (which lists all logged in users) and pipe it to the command `grep mizbicki` (which will filters the output to only lines containing `mizbicki`).

**Comment by mikeizbicki** [comment]
I'm reopening the issue so that it's a bit easier for other students to discover who might have this same problem.

**Comment by Tonnpo** [comment]
I used `last` command instead of `finger` to get the number of times user logged in
