### ISSUE TITLE
Permission denied in twitter MapReduce homework

### ISSUE THREAD

**Issue by leafsphere** [mikeizbicki/cmc-csci143#98]
I'm starting the second homework, and after I forked and cloned the [twitter_coronavirus](https://github.com/mikeizbicki/twitter_coronavirus) repo, I tried Background Task 2, which is running 

```
$ ./src/map.py --input_path=/data-fast/twitter\ 2020/geoTwitter20-04-01.zip
```

However, I get an error: 
```
/src/map.py: Permission denied
```

Is there any way I can fix this?

**Comment by mikeizbicki** [comment]
We discussed this in lecture today, but the short answer is that you need to run the `chmod u+x` command whenever you get a permission denied error running a file.

**Comment by iamasteriix** [comment]
@mikeizbicki Meanwhile, this might be trivial, but when I execute `map.py`, I get the error
```
Traceback (most recent call last):
  File "src/map.py", line 42, in <module>
    with zipfile.ZipFile(args.input_path) as archive:
  File "/usr/lib/python3.6/zipfile.py", line 1113, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/data-fast/twitter 2020/geoTwitter20-02-16.zip'
```

**Comment by mikeizbicki** [comment]
The data files used to be stored on the NVME drives in the `/data-fast/twitter 2020` folder.  They are now stored on the RAID array in the `/data/Twitter dataset` folder.  Updating the location should fix the issue.  I assume there's probably also a mistake in the instructions somewhere specifying the wrong l ocation, and so I'd appreciate a pr fixing that.
